### ISSUE TITLE
multiple polyLine handling

### ISSUE THREAD

**Issue by jgroom33** [dburles/meteor-google-maps#100]
The following capability does not appear to be supported when using the Blaze implementation:
http://codepen.io/anon/pen/EPNLWO

During the remove, only the last polyLine is removed from the map.

ployLine creation:

``` javascript
for (var i = 1; i < 5; i++) {
            routePolyline[i] = new google.maps.Polyline({
              path: routeCoordinates[i],
              strokeColor: routeDots[i].color,
              strokeOpacity: 1.0,
              strokeWeight: 2,
              map: GoogleMaps.maps.addRouteMap.instance
            });
};
```

polyLine removal:

``` javascript
    for (var j = 0; j < 5; j++) {
        routePolyline[j].setMap(null);
    }
```

real-world attempt:
https://ide.c9.io/jgroom33/lalalala/

client/templates/addRoute.js has a comment mentioning:
https://github.com/dburles/meteor-google-maps/issues/100

**Comment by dburles** [comment]
Hey @jgroom33 I think I need more context? do you think it's a problem specific to this package or a question on Google maps itself?

**Comment by dburles** [comment]
Closing this one as it's a couple of weeks old, @jgroom33 feel free to reopen it if need be.
