### ISSUE TITLE
Cannot read property 'PlacesService' of undefined

### ISSUE THREAD

**Issue by dhobla007** [dburles/meteor-google-maps#101]
While using this package and using Place service i am getting following error.
Is package does not support Pace service calls?
or if yes what is way to fix this issue

Thanks,

**Comment by dburles** [comment]
Hey @dhobla007 not much info to go on here but judging by the error I'm guessing it means that `google` is undefined. This means the script has not yet loaded.

https://github.com/dburles/meteor-google-maps#loaded

**Comment by dburles** [comment]
@dhobla007 did you end up resolving this? going to close the issue as it's a couple of weeks old
