### ISSUE TITLE
React: error rendering markers, zoom controls take several minutes

### ISSUE THREAD

**Issue by danielksato** [dburles/meteor-google-maps#105]
I'm having an issue with the map rendering, but not loading the zoom controls - I get empty white boxes instead. Markers don't render either - I eventually (after several minutes) get the error message: 

"Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'"

At that point, the map controls do render, but the markers never do.

Additionally, I can drag the street view 'pegman' icon to a street (whether or not it's rendered), but the street view never loads - it's just controls on a grey background.

The react example code works perfectly in my environment, with all the same versions of all the same packages. Any idea what could be causing this?

**Comment by dburles** [comment]
Look for a global CSS height property on the img tag

**Comment by danielksato** [comment]
Thanks for jumping in so quickly! Unfortunately, it doesn't seem to be a CSS issue - I removed all CSS and replaced it with googlemaps-react.css from your example, and I'm still having the same issue. Again, the controls _eventually_ render, after several minutes. Any other directions you might be able to point me in?

**Comment by dburles** [comment]
Hmm very strange, just to clarify, the example app works perfectly fine? But the error occurs in the context of your own application?

**Comment by danielksato** [comment]
That's correct. I double-checked that I had the same versions of meteor and all its packages in both cases. I'll try to get it deployed when I get home tonight, so I can give you a better idea what's going on. This is a school project, so my teammates and I would be grateful for any insight you might be able to give us.

**Comment by dburles** [comment]
Sure thing, if you can put the source up too that would be helpful

**Comment by danielksato** [comment]
It's live at http://dksato.com:3000/newevent and the source is at https://github.com/Polliwog-Labs/minnow_2. The project is a collaborative trip planning app, so there's a lot of other stuff going on, but the only component that depends on google maps is Event, defined in client/componets/event.

Thanks again!

**Comment by dburles** [comment]
I think the most likely culprit is Ionic, I don't have time to dig any further as I don't believe the issue is specifically related to this package, good luck!

**Comment by danielksato** [comment]
I was able to reproduce the problem with ionic completely removed, so I don't think that's it. 

After adding optimized: false to the marker, I was able to get it to render at the same time as the map controls, several minutes after the map itself renders. I appreciate your help so far, and I do agree with you that whatever is going wrong is probably happening upstream of this package. Still, if anything comes to mind, please let me know. Thanks again!

**Comment by dburles** [comment]
Interested to know if you found the source of the problem @pretzelface!

**Comment by danielksato** [comment]
I never did - the problem got passed around our group, and nobody could quite figure it out. We tried different ways of loading the Google Maps API library, with the same result. Setting optimize:false on the markers caused them to show up, eventually, but it still takes several minutes, like it's waiting for something to time out.
