### ISSUE TITLE
Modal Loading Issues

### ISSUE THREAD

**Issue by chackerian** [dburles/meteor-google-maps#107]
Google Maps only displays properly when the browser window has been manually resized or when the developer tools window is opened. Until these things occur, google maps displays grey as if it is unloaded. This is only happening on my modals and not on non modal pages.

Looks like this has been asked before in #65 , have you since found anything to make this work?

**Comment by dburles** [comment]
Hey @chackerian I believe the underlying issue is one with google maps itself and it being unable to correctly calculate the container height. I'm sure I've seen some info out there on the problem and how to fix it.

**Comment by JayMc** [comment]
If you have the map placed in a template in the modal, try calling
GoogleMaps.ready() in the onCreated or rendered function. Or if the modal
has some sort of onShow event use that.

**Comment by chackerian** [comment]
I tried all those options and they didn't seem to help.

**Comment by Rathius** [comment]
Have you tried having the modal itself as a template in a separate file and then call the template from within the modal? Something like

<modal>

```
{{> modalMap}}
```

</modal>

**Comment by Rathius** [comment]
That should be
    < modal>

```
    {{> modalMap}}

</modal>
```

**Comment by chackerian** [comment]
Yeah, I tried. That doesn't seem to work either.

**Comment by felipesmendes** [comment]
I have same issue, exacly what @chackerian said.

**Comment by dburles** [comment]
Tried setting a static height on the `.map-container` ?

**Comment by felipesmendes** [comment]
Yes, like in example with height 500px

Enviado via iPhone

**Comment by dburles** [comment]
I think the root of the problem is whatever Javascript is involved with calculating the height of the modal interfering with the maps own calculation, something like:
1. Modal window loads with no initial height set (say 0px)
2. The Google map then initialises and the map view calculates its height based on its surrounding container (which is 0px)
3. Modal window then calculates the correct height, however the map canvas does not react to that change.

Trigger a map resize by hooking into the modal event, some pseudocode:

``` js
modal.on('show', () => google.maps.event.trigger(GoogleMaps.maps.exampleMap, 'resize'));
```

Google around for Google map modal for more info. The root cause of the issue certainly isn't caused by this package itself.

**Comment by felipesmendes** [comment]
I triggered resize event on modal show and still loading maps just when dev
tools opens

_Att,_

_Felipe Silveira Mendes_Twitter https://twitter.com/felipesmendes -
Linked-In http://www.linkedin.com/pub/felipe-silveira/33/247/496
_Web Developer_
_(31) 8370-9090 (Claro)_
_contato@felipems.com.br contato@felipems.com.br_

2016-02-27 21:12 GMT-03:00 David Burles notifications@github.com:

**Comment by felipesmendes** [comment]
There's something else I can try?

**Comment by dburles** [comment]
@felipesmendes there may be someone who can help out over on gitter https://gitter.im/dburles/meteor-google-maps

**Comment by matejicekme** [comment]
Hi there,
Having the same problem, found a solution :).

Just trigger your map template with "Blaze.renderWithData" on modal button opener :

```
'click .activator': function(event) {
        var data = Template.currentData(self.view);
        Blaze.renderWithData(Template.MyMap, data, $("#gmap-container")[0])
    }
```

On your MyMap html template : 

```
<template name="MyMap">
    {{> googleMap name="myMap" options=myMapOptions}}
</template>
```

On MyMap JS : 

```
Template.MyMap.onCreated(function() {
    GoogleMaps.load({ // TODO : your Gmap Initialization });
    GoogleMaps.ready('myMap', function(map) {
        // Add a marker to the map once it's ready
        var marker = new google.maps.Marker({
            position: map.options.center,
            map: map.instance
        });
    });
});

Template.MyMap.helpers({
    myMapOptions: function() {
        var data = Template.currentData(self.view);
        if (!data) return;
        // Make sure the maps API has loaded
        if (data && GoogleMaps.loaded()) {
            // Map initialization options
            return {
                center: new google.maps.LatLng(data.location.geopoint.lat, data.location.geopoint.lng),
                zoom: 17
            };
        }
    }
});
```

And here the trick, your modal has to be on relative position, and your "#gmap-container" (where you render your map with Blaze.renderWithData) has to be on position: absolute; width:100%; height: 100%;
Here's my SCSS file sample :

```
.card-reveal { padding:0;
        #gmap-container { width:100%; position:absolute; top:0; left:0; height:100%; }
    }
```

Hope it helps ;) !

C ya
