### ISSUE TITLE
Fails silently (blank canvas - no error) - SOLVED

### ISSUE THREAD

**Issue by PolarisWT** [dburles/meteor-google-maps#108]
I had this issue and had a hard time figuring out where the error was.  I finally ended up installing the package manually in my meteor project (/packages) and found that when the options object is not set properly, it just returns undefined without a message on the client or server.

Quick version: If you just get a blank canvas area and no errors (in console) are presented - check that you are indeed setting your options object properly.

Longer version:
In this case, I was loading the options in the template helper from a search in a collection.  

**map.html**

``` html
<div class="map-container">
   {{> googleMap name="map" options=mapOptions}}
</div>
```

**map.js**

``` javascript
Template.map.helpers( {
  mapOptions: function(){
    if( GoogleMaps.loaded() ){
      var loc = Collection.findOne( { <selector> } );
      if( loc ){
        return { center: new google.maps.LatLng( loc.lat, loc.lng ),
                 zoom:   8 };
      }
    }
  }
});
```

The _selector_ I had was not found in the collection (my bad).  When this result ("undefined") is passed to the Template.googleMap.onRendered() as data.options - it breaks out of this function (as it should) but there is no error message on the server or client thus making it harder to know where to start debugging.  

**/meteor-google-maps/google-maps.js**

``` javascript
...
if (! data.options) {
  return;
}
...
```

Also, my code (at that time) didn't have an appropriate fallback for selectors that did not return a document - it does now! :)

Hope this helps someone else!
(PR on the way to issue a console error message upon undefined options )

**Comment by dburles** [comment]
Hey @PolarisWT originally it returned an error if no options were found, but that limited the ability to make use of reactivity within the `mapOptions` helper just like what you're doing there with `findOne`. So the way it works now is instead of throwing an error when it sees no options, it will only initialise the map once an object is returned.

Here's the commit that introduced this change: https://github.com/dburles/meteor-google-maps/commit/d6e30188099a088e7ae4cccdddb13adc1f6ae98c

**Comment by PolarisWT** [comment]
Ahhh, I see!  That makes sense...  Thanks @dburles 

I did notice a few possible similar issues others had with something similar to this (but they didn't give much detail).  So, I am hoping others can glean a little on where to start looking when the map doesn't present as expected.

Closing this issue and PR cancelled.

Cheers!

**Comment by dburles** [comment]
I should probably better explain its behaviour in the docs :)
