### ISSUE TITLE
Markers clustering

### ISSUE THREAD

**Issue by thiagoterleski** [dburles/meteor-google-maps#109]
Hi, how can i use markers clustering in the map?

**Comment by MichalW** [comment]
http://jsfiddle.net/B3a86/2/

**Comment by dburles** [comment]
Hey @thiagoterleski you may find further help over on gitter https://gitter.im/dburles/meteor-google-maps

**Comment by thiagoterleski** [comment]
thanks @MichalW  and @dburles !
