### ISSUE TITLE
Passing ReactiveVar for center in map options reinitializes the map on variable change

### ISSUE THREAD

**Issue by kontur** [dburles/meteor-google-maps#11]
Hey,

I noticed that it would be really nice to pass in the map center in the options as a reactive value, which would automatically update the map center when changed. 

Conversely, when you now do pass in a reactive value, the map actually gets reinitialized whenever the value updates, which seems undesirable. 

Any thoughts on this?

**Comment by dburles** [comment]
Hey @kontur the options are for initialising the map with `new google.maps.Map`. I think what you're looking to do is interact with the API (specifically using `map.setCenter`) within the `GoogleMaps.ready` callback. See the example below:

``` js
Template.body.helpers({
  exampleMapOptions: function() {
    // Make sure the maps API has loaded
    if (GoogleMaps.loaded()) {
      // We can use the `ready` callback to interact with the map API once the map is ready.
      GoogleMaps.ready('exampleMap', function(map) {
        Tracker.autorun(function() {
          if (Session.get('lat') && Session.get('lng'))
            map.setCenter({ lat: Session.get('lat'), lng: Session.get('lng') });
        });
      });

      // Map initialization options
      return {
        center: new google.maps.LatLng(-37.8136, 144.9631),
        zoom: 8
      };
    }
  }
});
```

Hope that helps

**Comment by kontur** [comment]
Yes, maybe the right way to update is like that, and that is how I've implemented it where I've used this package.

I guess the issue I am reporting is that when you do use a ReactiveVar in the options' return the map will reinitialize whenever the value changes. On the other hand, that made me think that using a reactive var to update the map options might be the meteor way to do things, so that's where the other suggestion comes from.

**Comment by dburles** [comment]
It would make sense to use a reactive value within the returned options if you wished to re-initialise the map with that new value, otherwise the above pattern is definitely the way to go.

**Comment by kontur** [comment]
Roger that, I'll close the issue. Thanks for the great package :)

**Comment by dburles** [comment]
Thanks
