### ISSUE TITLE
GoogleMaps.ready not firing on android (cordova)

### ISSUE THREAD

**Issue by shadowzick** [dburles/meteor-google-maps#111]
Hi dburles, I was wondering why the GoogleMaps.ready function is not firing on android, I already tried adding the access rules but it's still not working, I only get a blank page. Please help. Thanks.

**Comment by dburles** [comment]
Hey @shadowzick have you tried with the demo app? https://github.com/dburles/meteor-google-maps-demo

**Comment by shadowzick** [comment]
@dburles will the demo app work with running meteor run android-device? sorry for this noob question

**Comment by dburles** [comment]
@shadowzick Yeah just add-platform first!

**Comment by shadowzick** [comment]
@dburles I've tried the demo app on mobile and it works fine, I think the problem was on my code but not so sure where. I'll let you know when I found out the problem. Thanks!

**Comment by dburles** [comment]
Join here others may help out too https://gitter.im/dburles/meteor-google-maps

**Comment by shadowzick** [comment]
Nice! Thanks :+1:

**Comment by shadowzick** [comment]
It now works, I was wondering why there were no error logs turns out the problem was on my CSS because I was using vh. Anways, thanks! @dburles
