### ISSUE TITLE
inherit using prototype from google.maps.OverlayView

### ISSUE THREAD

**Issue by jupiterkenji** [dburles/meteor-google-maps#114]
I try to create context-menu by inheriting from google.maps.OverlayView() like so:

```
ContextMenu.prototype = new google.maps.OverlayView();
ContextMenu.prototype.onAdd = function() {
...
}

```

But it keeps saying google is not defined.
I have been googling and people suggesting: 
if (GoogleMaps.loaded()) {..}
But sounds a bit weird.

Does anyone have any knowledge on this?

Thank you. Great package!

**Comment by dburles** [comment]
Hey @stewiegaribaldi that's right you'll need to use that function to check whether the library has loaded before interacting with it. Typically you might attach it to the template that displays the map.

``` js
Template.myMap.onCreated(function() {
  this.autorun(() => {
    if (GoogleMaps.loaded()) {
      ContextMenu.prototype = new google.maps.OverlayView();
      ContextMenu.prototype.onAdd = function() {
        // ...
      }
    }
  });
});
```

**Comment by jupiterkenji** [comment]
Thank you @dburles , it works great!
