### ISSUE TITLE
"Unable to display a Google Maps element" in iOs

### ISSUE THREAD

**Issue by lpender** [dburles/meteor-google-maps#115]
I get the following error in iOs when I input my Google Maps API Key:

"This page was unable to display a Google Maps Element. Please contnact the site administrator. If you are the administrator of this site, please check the JavaScript console or check the following page for troubleshooting: http://g.co/mapsJSApiErrors'

I fixed this issue in Chrome by adding my domain to the domain whitelist in the Google API Manager.

I tried adding the following addresses to no avail:

```
*.mywebsite.com
meteor.local
```

Thoughts?

**Comment by dburles** [comment]
Hey @lpender does this help? https://github.com/dburles/meteor-google-maps#mobile-platforms

**Comment by lpender** [comment]
Hey,

I'm afraid not. The whitelist issue is in the other direction--I have to enter a domain whitelist into the _Google Developer interface_.

I have to whitelist whatever domain iOs is running the app from--I just can't figure out what that might be...

Thanks!

**Comment by lpender** [comment]
Got it, I had to add `myapp.herokuapp.com` to the google whitelist. Apparently that's where the request was coming from.

**Comment by lpender** [comment]
In development, this url appears to be `localhost:12000` (at least for me)

**Comment by lpender** [comment]
Add the result of this to your google API whitelist `dig myapp.com cname +short`
