### ISSUE TITLE
Marker not show while click on map

### ISSUE THREAD

**Issue by deepupathak** [dburles/meteor-google-maps#117]
Hello,
While click on map, markers is not shown on the map. Please help me for this issue.

thanks in advance.

**Comment by dburles** [comment]
Hey @deepupathak not a lot to go on there, is there a specific bug you've encountered with the package?

**Comment by deepupathak** [comment]
sorry for disturb you,Its my fault. Its running perfectly now.

**Comment by deepupathak** [comment]
I want to implement marker clusterer in the map. Please help me and suggest for the same.

**Comment by dburles** [comment]
Probably best to discuss with the people on [gitter](https://gitter.im/dburles/meteor-google-maps?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) as here is for reporting bugs and feature requests for the package
