### ISSUE TITLE
Brownser refusing to execute line 72 of dburles_google-maps.js because of Content Security Policy

### ISSUE THREAD

**Issue by filipeportes** [dburles/meteor-google-maps#12]
browser showing the following message:

Refused to load the script 'https://maps.googleapis.com/maps/api/js?v=3.exp&callback=GoogleMaps._initialize' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".

and points to this code:

``` javascript
    script.src = 'https://maps.googleapis.com/maps/api/js?' + params +                         
      '&callback=GoogleMaps._initialize';                                                      

    document.body.appendChild(script);     
```

**Comment by dburles** [comment]
Hey @filipeportes is this in production? If so may I check the site? It looks as though the server is sending a content security policy within the response header

**Comment by JVercout** [comment]
Hi, 

I'm using the browser-policy meteor package. 

I've got the same error here:

```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'
```

I've got the following configuration files in Meteor.startup(): 

```
    BrowserPolicy.content.allowOriginForAll('fonts.gstatic.com');
    BrowserPolicy.content.allowOriginForAll('*.googleapis.com');
    BrowserPolicy.content.allowOriginForAll('maps.gstatic.com');
```

but to make it works, I need to add a (and _I don't want to_) 

```
BrowserPolicy.content.allowEval('https://ajax.googleapis.com'); 
```

Any ideas? 

Jerome
