### ISSUE TITLE
All blank with no error message

### ISSUE THREAD

**Issue by NanIsNotANum** [dburles/meteor-google-maps#124]
Hi @dburles ,

I installed your package, and follow your tutorial, but the map just doesnt show up @@
since theres no error message at, I would like to know if you can take a look and give me some suggestion?

Heres my code:

in template html file
**<div class="map-container">
    {{> googleMap name="exampleMap" options=exampleMapOptions}}
  </div>**

in .css file 

**body, html {
    height: 100%;
    width: 100%;
}
.map-container {
    width: 100%;
    height: 100%;
}**

in .js file
**Template.hello.onCreated(function helloOnCreated() { 
        GoogleMaps.load({key:"my key"});
        GoogleMaps.ready('exampleMap', function(map) {

```
  // Add a marker to the map once it's ready

    var marker = new google.maps.Marker({
    position: map.options.center,
    map: map.instance
});
```

  });
});
    Template.hello.helpers({

```
   exampleMapOptions: function() {
  // Make sure the maps API has loaded
  // Map initialization options

    return {
        center: new google.maps.LatLng(-37.8136, 144.9631),
        zoom: 13
    };
 }
```

});**

Thanks a lot :)

**Comment by dburles** [comment]
Did you wrap the map template in `<div class="map-container"></div>`?

**Comment by NanIsNotANum** [comment]
Hello, I forgot to attach the part, but Yes I do wrap the template in<div class="map-container"></div> !

**Comment by dburles** [comment]
I'd suggest to try run this https://github.com/dburles/meteor-google-maps-demo and compare it with your own app for any differences that may be causing the problem

**Comment by NanIsNotANum** [comment]
Hi there, I tried to compare with the demo code and my code, I didnt see how I could improve my code. However, these days after I edited my code from other parts, the map works! but unfortunately I still have no idea which other parts were blocking the map. I will report you once I am sure. I will close the issue for now. Thanks a lot for the help!
