### ISSUE TITLE
Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by alexandrzavalii** [dburles/meteor-google-maps#125]
This line throws an error

```
        center: new google.maps.LatLng(-37.8136, 144.9631),
```

Is there a workaround ?

**Comment by dburles** [comment]
Hey @alexandrzavalii I need more info!

**Comment by alexandrzavalii** [comment]
Yeah, I am sorry @dburles . I set the options in the meteor helper as in the documentation and it throws an error, even though the map is loaded.

```
mapOptions: () => {
    if (GoogleMaps.loaded()) {
      return {
        center: new google.maps.LatLng(-37.8136, 144.9631),
        zoom: 15
      };
    }
  }
```

**Comment by dburles** [comment]
Not sure what's going wrong there, try [the example app](https://github.com/dburles/meteor-google-maps-demo) and see if that runs okay for you. That might help you find the cause of the problem.

**Comment by alexandrzavalii** [comment]
I did exactly as in the example app.
This error is still there. Specifically this line of code is causing it.
`center: new google.maps.LatLng(-37.8136, 144.9631),`
I tried doing it with 
`location: new google.maps.LatLng(-37.8136, 144.9631)` or `location: ["-37,"144"]`
and I still get the same error.

**Comment by dburles** [comment]
Did the example work okay or did you get the same error?

**Comment by alexandrzavalii** [comment]
It did not.I am getting the same error.

**Comment by NicholasEli** [comment]
For 'x', does it happen to be your latitude coordinate? I am getting the same issue right now while in production. 

http://wsyacht.herokuapp.com/

**UPDATE**

I solved the issue by turning my coordinates to an integer, as I was returning the coordinates from a collection stored as a string.

**Comment by code4cake** [comment]
@NicholasEli how are you saving your `lat` and `lon` values in your collection if you don't mind me asking.

**Comment by NicholasEli** [comment]
Hmmm, I was wrong. The issue seems to persist, but was working temporarily. But I am storing them in a pretty simple traditional sense:

```
latlng: {
     lat: '44.21321646161,
    lng: '-125.221981853
}
```

*\* UPDATE **
It seems this has an issue while working with FlowRouter. On initial page load the error is there (production only), but if I navigate to another page/route and then navigate back the error is gone and everything works fine.

**Comment by dburles** [comment]
@NicholasEli sounds like your data might not yet be loaded at the time you're trying to reference it

**Comment by code4cake** [comment]
@NicholasEli how are you attaching them to your object. or how are you computing them? Or are you just writing the numbers. Thanks

**Comment by NicholasEli** [comment]
@dburles thats kinda what I am thinking.

@dantesolis they are static numbers, so I am just writing them in.

**Comment by dburles** [comment]
Post a link to a repo containing as little code as possible that reproduces the problem

**Comment by NicholasEli** [comment]
Confirmed, the data was not being loaded at time or reference.

**Comment by ankitappuria** [comment]
Hello,
I am facing same issue.I am getting Cannot read property 'x' of undefined error when navigating to other page and returning back to map page.If I am loading map page it is working fine. Please help me out.

**Comment by dburles** [comment]
@ankitappuria can you post some code to provide some context?

**Comment by ankitappuria** [comment]
I am getting error in helper of option due to center.

```
 exampleMapOptions: function() {

        // Make sure the maps API has loaded
        if (GoogleMaps.loaded()) {
            // Map initialization options
            return {
                center: new google.maps.LatLng(20.5937, 78.9629), **//this line of code giving error**
                zoom: 8,
                styles:mapStyle
            };
        }
    },
```

**Comment by dburles** [comment]
@ankitappuria if you could, can you provide a link to a repo with a complete app I can run? (if you can please only include code that is relevant to the issue)

**Comment by ankitappuria** [comment]
Thanks issue was in variable declaration I have solved it.
