### ISSUE TITLE
no plugin found for google-maps.html

### ISSUE THREAD

**Issue by schabluk** [dburles/meteor-google-maps#126]
```
While building for web.browser:
   error: no plugin found for google-maps.html in dburles:google-maps; a plugin for *.html was active when it was published but none is now
```

Error thrown from: https://github.com/meteor/meteor/blob/master/tools/isobuild/compiler-plugin.js

Meteor version 1.4 with SSR.

**Comment by dburles** [comment]
I'm happy to accept a PR for this one if you figure out the cause

**Comment by nunof07** [comment]
This was happening to me in some projects.

The ones that were failing were using `templating@1.0.11`. I manually changed in the Meteor versions file to `templating@1.2.15` and now it works.
