### ISSUE TITLE
Map is black on Cordova and Meteor 1.4.2-beta9 on iOS10

### ISSUE THREAD

**Issue by adamgins** [dburles/meteor-google-maps#129]
HI,

trying to get maps working on iOS10 (via Xcode 8).

Pre iOS10 / Meteor 1.3 my code works fine. It seems like a browser policy issue, although I have the policy specified for this package. 

I can view the map on mobile on iOS, it's just in Cordova that it does not show up. I can't see anything on the console (via XCode). Any ideas pls?

OK, my load command is not working on Cordova:

```
Meteor.startup(function() {

    GoogleMaps.load({ key: '<my key>', libraries: 'places'});
});

```

I thought Meteor.startup should only run once Cordova is ready... thoughts?

If I move it on the `onRendered` it works... just not sure why Meteor.startup is not working with Cordova/iOS 10, when it's always worked prior to this.

**Comment by adamgins** [comment]
if I view the markup on the

Via browser:

![screen shot 2016-10-07 at 1 34 35 pm](https://cloud.githubusercontent.com/assets/7233741/19177247/010be1e6-8c93-11e6-8ee9-b7c166a2f206.png)

Cordova

![screen shot 2016-10-07 at 1 33 30 pm](https://cloud.githubusercontent.com/assets/7233741/19177250/02d964b2-8c93-11e6-885f-0059c086fbff.png)

**Comment by guidouil** [comment]
do you have the `App.accessRule('*');` or at list open to google.com and gstatic.com in your `mobile-config.js` file ?

**Comment by adamgins** [comment]
Yes. Actually got a note back from @dburles that onRendered probably better place to run the load command. So will close this now as that worked.
