### ISSUE TITLE
Google Places API

### ISSUE THREAD

**Issue by FrancoJ** [dburles/meteor-google-maps#13]
This isn't an issue, but just a question:

I've been using this plugin with the mdg:geolocation plugin, and they work well together. Now just trying to find out all of the options I can use with this plugin by adding extra libraries such as Places like in your example.  

Basically i'm just trying to recreate this example and curious if this plugin is capable of this sort of stuff as well?
https://developers.google.com/maps/documentation/javascript/examples/place-search

**Comment by dburles** [comment]
Hey @Frankiezzy looks to me like it'll work just fine, you should be able to figure out how to work it in by looking at the example in this package readme.

**Comment by FrancoJ** [comment]
@dburles thanks for the quick response.

**Comment by avani19** [comment]
Hey, I am trying to get the location autocomplete for form i am using in my Meteor app. How can i get the location autocomplete for the form using Meteor?
