### ISSUE TITLE
Template with googleMap inside is rendered twice

### ISSUE THREAD

**Issue by naho2081** [dburles/meteor-google-maps#136]
Template which contains googleMap container is always rendered twice. How to stop this behavior?

googleMap is inserted as follows:

HTML
```
<template name="mapContainer">
    <div class="map">
       {{> googleMap name="googleMap" options=googleMapOptions}}
    </div>
</template>
```

JS (CoffeeScript)
```
Template.mapContainer.helpers
	googleMapOptions: ->
		if (GoogleMaps.loaded())
			center: new google.maps.LatLng(@x, @y)
			zoom: 10


Template.mapContainer.rendered = ->
	GoogleMaps.load
		key: "secret_key"
	GoogleMaps.ready 'googleMap', (map) ->
		marker = new (google.maps.Marker)(
			position: map.options.center
			map: map.instance)
```

**Comment by dburles** [comment]
Hey @naho2081 need a bit more info! what do you mean by rendered twice? the callback fires twice?

**Comment by naho2081** [comment]
Hi @dburles .
Yes, you can check it out [here](https://fastfred.de/shop/shop-de).
And [here](https://fastfred.de/shop/shop2-de) is how same page but without GoogleMap is rendered.

**Comment by dburles** [comment]
@naho2081 what is the problem you're seeing as a result of the template rendering twice?

**Comment by naho2081** [comment]
@dburles screen is flashing twice while page is loaded and user may notice that

**Comment by dburles** [comment]
Are you able to reproduce the same problem in an isolated application? i.e [the simple example app](https://github.com/dburles/meteor-google-maps-demo)

**Comment by dburles** [comment]
I do see the flash on the link you provided

**Comment by naho2081** [comment]
I just fixed the issue.
The reason was that googleMap inserted link to google stylesheet into the `<head>` causing page reload.

In my case link was
```link(rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700")```

I have manually added this link into the head of the template and issue was fixed.

Probably this could be somehow considered in further plugin versions.

Thanks for help @dburles !

**Comment by dburles** [comment]
Strange, it's not something I've noticed elsewhere, if you're able to reproduce it in an isolated application that might narrow down the issue, I feel like the fact that your page content flashes something else might be going on there!

**Comment by naho2081** [comment]
@dburles see my comment above.

**Comment by dburles** [comment]
Oh yeah but I mean like the fact that it's affecting the existing fonts on your page in particular. I haven't seen that happen on other sites that use this maps package. But glad you found a solution!

**Comment by naho2081** [comment]
Yes, those Google fonts slightly differ from used on the page. That's why maybe googleMap downloads fonts it wants to use :)
