### ISSUE TITLE
load alreadyLoaded option

### ISSUE THREAD

**Issue by lukemadera** [dburles/meteor-google-maps#14]
Great package @dburles - thanks! I'm using other google maps functionality (places autocomplete specifically) and so there's a conflict or "double loading" of google maps currently. I got around this by calling initialize myself:

``` js
if (Meteor.isClient) {
  Meteor.startup(function() {
    // GoogleMaps.load({ v: '3', libraries: 'places' });
    GoogleMaps._initialize();
  });
}
```

But it would better if this was an option that could be passed to `GoogleMaps.load` to skip loading the google maps script if it has already been loaded elsewhere.
Happy to submit a pull request if you'd like.

**Comment by dburles** [comment]
Hey @lukemadera as you probably already know we're loading the maps library asynchronously.  `GoogleMaps._initialize` is called by the maps library itself when it finished loading as we pass it in the [`callback` query param](https://github.com/dburles/meteor-google-maps/blob/master/google-maps.js#L10)

Calling `GoogleMaps._initialize` manually could run into problems as there's no guarantee the _other_ maps library has loaded when you call it. Particularly if the other library had passed its own callback param. In that case you would have to hook into that to call `GoogleMaps._initialize`.

I feel that passing an option into `load` may simply further hide this problem and lead to frustration when things just won't work. I'll ruminate.

Also, I just checked out your package, maybe it could benefit from using this package? Just an idea :)

**Comment by lukemadera** [comment]
Thanks for the details @dburles . I haven't had a problem thus far with calling `GoogleMaps._initialize` manually but I agree there could be a timing issue there.

And I actually already tried using your package to load google maps but it resulted in a `Google is undefined` error - potentially the same timing issue?

Either way though, I think packages should NOT require auto loading other (3rd party) dependencies such as google maps. Give the option, sure, but don't force it. Give the developer the option to load the other dependencies on his own and leave it up to him to ensure the timing is handled. Can easily put that in the documentation for a new `alreadyLoaded` option, no?

**Comment by dburles** [comment]
I agree. Perhaps I could expose `GoogleMaps.initialize` which can be called just the same (but documented). 

Were you looking for `GoogleMaps` or `google` (lowercase) ?

**Comment by lukemadera** [comment]
Sounds great! Thanks!
And yeah sorry I was just typing from memory - not sure the exact name of the error, just know I got one that had to do with Google Maps not being loaded properly ;)

**Comment by dburles** [comment]
Done

**Comment by lukemadera** [comment]
Awesome thanks @dburles !
