### ISSUE TITLE
cordova app - unable to select  / click in the suggestion list

### ISSUE THREAD

**Issue by steven-tib** [dburles/meteor-google-maps#140]
Hi, I'm testing my app on iOS (meteor run ios-device), the map displays correctly but when typing a location, the autosuggestion list appears but when I click on one of the suggestion it closes the list without selecting my choice. 

When typing something and hitting enter, the location is correctly selected though. 
Just the problem with auto-suggested list click/selection. 

same behavior in the iOS simulator from xcode. 
It doesn't happen when using chrome dev-tool to simulate mobile view in browser.

Any clue? Is someone experiencing the same behavior?

**Comment by steven-tib** [comment]
@dburles any clue on this issue? if you need more details please let me know, thanks for your help

**Comment by dburles** [comment]
Not sure on that one @steven-tib sorry. You might have more luck asking here https://gitter.im/dburles/meteor-google-maps or perhaps on stackoverflow.
