### ISSUE TITLE
Near by search

### ISSUE THREAD

**Issue by varunajmera0** [dburles/meteor-google-maps#142]
I am getting this error on place library when i want to search nearby.
![image](https://cloud.githubusercontent.com/assets/22893376/23607774/380f161c-028c-11e7-9595-37f1c4b22fef.png)

**Comment by dburles** [comment]
@varunajmera0 Most likely it's an issue relating to the Google API itself rather than this package specifically. You may have better luck asking on stackoverflow. If you do believe it's caused by a bug in this package I'll reopen.
