### ISSUE TITLE
Every time GoogleMaps.load() run <head> get additional copy of <style> for google maps

### ISSUE THREAD

**Issue by ghost** [dburles/meteor-google-maps#149]
Grretings. In my project I happen to use Google search box in forms. Form itself called when I click on table row, and I noticed that `<head>` tag get updated every click. Putting break on subtree modification showed code related to google maps which load additional `<styles>` tag in `<head>`. Maybe need to add check if styles loaded to not load it many times? Thanks.

**Comment by dburles** [comment]
Hey @Cherviakov do you have a simple reproduction I can look at? I don't think it would be caused by `GoogleMaps.load` as it should only run once

**Comment by ghost** [comment]
Tried to write simple test, cannot reproduce the way I explained before. Will look further into my project code.

**Comment by ghost** [comment]
It appeared to be error with google maps itself, but they refuse to take look into it saying we use 3d party packages. Not looked further in it myself, so let it be for now like this.
