### ISSUE TITLE
Problems Loading on Android Browser (Android > 4.2) & Iphone 4

### ISSUE THREAD

**Issue by pmwisdom** [dburles/meteor-google-maps#15]
Hey there, I've been attempting to use this on a whole slew of devices, and have found some combinations that simply will not load the map. 

Platforms that I have found not to load : 
Android  > 4.4 Cordova WebView and the Default Android Browser. (Chrome works)
iPhone 4 Cordova WebView. (iPhone 4s works).

Unfortunately there is no error I can give you, but I thought you might like to know. 

Sorry its so hard to reproduce, you would need an actual device with an older version of android.

**Comment by dburles** [comment]
Thanks @pmwisdom. I don't have access to those devices to test myself, but any more info you can dig up would be helpful.

**Comment by pmwisdom** [comment]
So I did more tests today, and I couldn't find any errors via adb for your package so I'm about 99% its just a css issue. The only reason I originally didn't think it was css was because it worked on the iPhone 4s and didn't on the 4, which I thought rendered in the exact same way.
