### ISSUE TITLE
Blaze-less version

### ISSUE THREAD

**Issue by Floriferous** [dburles/meteor-google-maps#157]
This is the only library we use that is still pulling in `blaze`, could there be a solution to use this package without the `templating` package, especially since many of us are using React?

* I could fork the package and republish it without the blaze portion
* Can we do better and keep using the same package?
  * Could there be a blaze-less branch that is published to another package name? That way new changes can easily be merged into both versions?

**Comment by dburles** [comment]
We could make the package have a weak dependency on `templating` and then only provide the `googleMap` template if you're using Blaze
