### ISSUE TITLE
options argument is not an object

### ISSUE THREAD

**Issue by bernatfortet** [dburles/meteor-google-maps#17]
I've copied line by line your example and I get this:

```
 Exception from Tracker recompute function: Error: [GoogleMaps - options argument is not an object]
    at null.<anonymous> (http://localhost:3000/packages/dburles_google-maps.js?b29ccf5b3fb2a7c5c3af7c92ba5ff35e30103d19:140:15)
    at http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1808:16
    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2043:12)
    at viewAutorun (http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1807:18)
    at Tracker.Computation._compute (http://localhost:3000/packages/tracker.js?517c8fe8ed6408951a30941e64a5383a7174bcfa:296:36)
    at Tracker.Computation._recompute (http://localhost:3000/packages/tracker.js?517c8fe8ed6408951a30941e64a5383a7174bcfa:310:14)
    at Tracker.flush (http://localhost:3000/packages/tracker.js?517c8fe8ed6408951a30941e64a5383a7174bcfa:440:14)
```

**Comment by dburles** [comment]
Hey @bernatfortet make sure that the inclusion tag for the map has the correct data context. The code in the example passes the helper through Template._body_. So if you have placed `{{> googleMap ...}}` within another template, it won't see the options argument.

**Comment by bernatfortet** [comment]
I'm using the exact same code that is seen on the documentation. 
New project as well.

``` html
<body>
  <div class="map-container">
    {{> googleMap name="exampleMap" options=exampleMapOptions}}
  </div>
</body>
```

``` js
Meteor.startup(function() {
    GoogleMaps.load();
});

Template.body.helpers({
  exampleMapOptions: function() {
    // Make sure the maps API has loaded
    if (GoogleMaps.loaded()) {
      // Map initialization options
      return {
        center: new google.maps.LatLng(-37.8136, 144.9631),
        zoom: 8
      };
    }
  }
});

Template.body.created = function() {
  // We can use the `ready` callback to interact with the map API once the map is ready.
  GoogleMaps.ready('exampleMap', function(map) {
    // Add a marker to the map once it's ready
    var marker = new google.maps.Marker({
      position: map.options.center,
      map: map.instance
    });
  });
};
```

**Comment by dburles** [comment]
Strange, try this demo project https://github.com/dburles/meteor-google-maps-demo

**Comment by tintoverano** [comment]
hello guys,

I'm getting this error in Chrome: only when switching to another tab and back to my tab with the map, there's no error after starting the app

but in Firefox the error is appearing at first load and then repeats

so far I didn't see any bad behavior in my app, it works as expected

tinto

**Comment by dburles** [comment]
@tintoverano I can't reproduce the issue on Chrome, are you able to reproduce using [the demo app?](https://github.com/dburles/meteor-google-maps-demo)

**Comment by tintoverano** [comment]
demo app works fine

in my case the problem seems to be related to calling Geolocation.latLng () from mdg:geolocation package inside the map options helper

I'm trying to refactor my code to get around this somehow

**Comment by dburles** [comment]
At a guess you would probably want to call that method reactively in an autorun based on `GoogleMaps.loaded()`

**Comment by tintoverano** [comment]
the function itself is reactive, so it is not necessary I think
I managed to refactor the code, it works in chrome but not yet fully in ff : )

**Comment by dburles** [comment]
well even so, you wouldn't want to call it before the maps API has loaded!

**Comment by tintoverano** [comment]
sure thing, thanks

**Comment by dburles** [comment]
Hey @bernatfortet did the demo project work? If not, what browser are you using?

**Comment by bernatfortet** [comment]
@dburles it works... I'll try to figure out what's changing. Thanks for you help!
