### ISSUE TITLE
adding MarkerWithLabel google package

### ISSUE THREAD

**Issue by tintoverano** [dburles/meteor-google-maps#18]
hi,

I think adding this Google package would be useful: http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerwithlabel/1.1.8/src/markerwithlabel.js

what do you think?

cheers,

tinto

**Comment by dburles** [comment]
hey @tintoverano you should be able to just drop it into say `client/lib` and start using it

**Comment by tintoverano** [comment]
I tried that and loading it via iron router as well, and perhaps I'm doing something wrong, but there's an error saying that this package doesn't find "google", though it should be there since your package loads it, I suspect it might be a load order problem

thanks,

tinto

**Comment by dburles** [comment]
In that case you might wish to drop in the script tag once `GoogleMaps.loaded()` fires

**Comment by tintoverano** [comment]
I see, ok I'll try that

thanks

**Comment by tintoverano** [comment]
I'm closing this because I stayed with a simpler solution for the moment.

thanks

**Comment by phongyewtong** [comment]
Any luck doing this on react?
