### ISSUE TITLE
How to destroy a newly added Marker

### ISSUE THREAD

**Issue by jennylia** [dburles/meteor-google-maps#21]
Hi David,

I added a marker like this:
    var lon = JSON.parse(results.content).coord.lon
        var lat = JSON.parse(results.content).coord.lat
        Session.set('lon', lon);
        Session.set('lat', lat);

```
    var marker = new google.maps.Marker({
        position: new google.maps.LatLng(lat, lon),
        map: GoogleMaps.maps.exampleMap.instance
    });
```

I can't destroy this marker when my lat lon has been updated.
Please give me a hint.

Thanks,
Jenny

**Comment by dburles** [comment]
There's a map's API call you can use to destroy a marker by passing in the marker instance.

**Comment by tintoverano** [comment]
simply call

```
myMarker.setMap (null);
```
