### ISSUE TITLE
Is there a way to insert the map to a div without using > googleMap 

### ISSUE THREAD

**Issue by barhum** [dburles/meteor-google-maps#23]
I am having an issue with reactivity while using the map, is this happening because it is a helper method?

I have read that many people resorted to loading the google map api like this:

```
var script = document.createElement('script');
script.type = 'text/javascript';
script.src = 'https://maps.googleapis.com/maps/api/js?v=3.exp' +
    '&callback=initialize';    
document.body.appendChild(script);
```

I got my main map to stop being reactive using this method but this does not play nice with iron-router.  The script persists on memory for redirects and if I am using > googleMap on other routes I get a script duplication.

Any suggestions on how can I work with the package and limit the reactivity of the map?

Thanks

**Comment by dburles** [comment]
Hey @barhum not exactly sure what problem you're describing, the map is loaded by the package just like the code you have pasted https://github.com/dburles/meteor-google-maps/blob/master/google-maps.js#L5-L12

So there's no need to write that code yourself, all you need do is call `GoogleMaps.load()` and it will ensure that the script loads (only once).

**Comment by barhum** [comment]
Thanks for the quick reply,

I tried adding GoogleMaps.load() to for my template in iron-router and it does load the google api in sources.  I am trying to insert the map from Template.foo.rendered but calling google.maps from rendered gives back undefined.  

I am trying to add it in the rendered portion to limit reactivity.

**Comment by dburles** [comment]
take a look at the examples, you want to be sure that the library is loaded before you reference `google.maps`. In order to do that you need to watch `GoogleMaps.loaded()` which is a reactive method, so place that inside a reactive computation, (autorun or template helper etc)

**Comment by dburles** [comment]
also take a look at the demo project https://github.com/dburles/meteor-google-maps-demo

**Comment by barhum** [comment]
Thanks @dburles , using Deps.autorun in rendered made it work!

**Comment by dburles** [comment]
I have a feeling that you're likely simply wanting to do what's described in the examples, specifically the `ready` callback, so do take a look at that.
