### ISSUE TITLE
Any way to add Circles?

### ISSUE THREAD

**Issue by livvyjeffs** [dburles/meteor-google-maps#24]
This is the code I tried based on the <a href="https://developers.google.com/maps/documentation/javascript/examples/circle-simple">Google Maps API example</a>:

 `var circleOptions = {
      strokeColor: '#FF0000',
      strokeOpacity: 0.8,
      strokeWeight: 2,
      fillColor: '#FF0000',
      fillOpacity: 0.35,
      map: map,
      center: new google.maps.LatLng(Session.get('latitude'), Session.get('longitude'),
      radius: 100
    };`

```
var cityCircle = new google.maps.Circle(circleOptions);
```

The error code in the console is this:

`Uncaught InvalidValueError: setMap: not an instance of Map`

**Comment by dburles** [comment]
`map` needs to be a map instance.

```
Template.body.created = function() {
  // We can use the `ready` callback to interact with the map API once the map is ready.
  GoogleMaps.ready('exampleMap', function(map) {
    // Put circle code in here
  });
};
```

**Comment by livvyjeffs** [comment]
Awesome, trick is to use `map.instance` thank you!

In my code I was also missing an end paren, so the code that works is:

`map: map.instance,`
`center: new google.maps.LatLng(Session.get('latitude'), Session.get('longitude'))`
