### ISSUE TITLE
on mobile: https://maps.googleapis.com/.... 404 Not found

### ISSUE THREAD

**Issue by JayMc** [dburles/meteor-google-maps#27]
With your example it works fine on desktop chrome but run as either virtual or physical Android apps I get: 404 Not found. For this url:

https://maps.googleapis.com/maps/api/js?v=3.exp&callback=GoogleMaps.initialize 

If I manually load that address in a mobile browser it opens without a problem.
Using Meteor 1.0.4

**Comment by dburles** [comment]
That's unusual, would appreciate it if you can look into it further

**Comment by JayMc** [comment]
Still looking, but doesn't appear to be your library.
Seems to be an issue with loading external libraries when on mobile device. If I manually add the head script tag for the google maps and lodash I get the same outcome (lodash = 404):

```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.5.0/lodash.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&callback=GoogleMaps.initialize"></script>
```

Above loads in libs for desktop but not mobile. Is there something different on mobile preventing loading libraries?

**Comment by dburles** [comment]
Not sure, maybe it's a platform restriction with external assets? Android development is not something I'm too familiar with.

**Comment by JayMc** [comment]
We got it, woot!

```
<access origin='*' />
```

was removed from config.xml in Meteor version 1.0.4 [see here](http://docs.meteor.com/#/full/App-accessRule)

To add a more appropriate rule create a file in the parent level called mobile-config.js and add the following for you map library to work:

```
App.accessRule('https://*.googleapis.com/*');
App.accessRule('https://*.google.com/*');
App.accessRule('https://*.gstatic.com/*');
```

**Comment by dburles** [comment]
Oh good find, I actually think now that these two issues are related: https://github.com/dburles/meteor-google-maps/issues/15 https://github.com/dburles/meteor-google-maps/issues/12

**Comment by boboci9** [comment]
Hi,

Can you tell me where should this config.js file be added if you are using the maps in a package? 
I get Uncaught ReferenceError: App is not defined both on client and on server side.

Thanks.

**Comment by dburles** [comment]
@boboci9 have a look here http://docs.meteor.com/#/full/mobileconfigjs

**Comment by boboci9** [comment]
Sorry I didn't know this was only for mobile apps, I am trying to find out why this package is not working in my project but it is a regular app in my case, and I have this same error.
I think I will repost the question in a new issue in this case, I thought it could be the same solution.

Thanks.

**Comment by dburles** [comment]
@boboci9 see if you can run the demo app https://github.com/dburles/meteor-google-maps-demo it may help with any problem you may have in your own app
