### ISSUE TITLE
events?

### ISSUE THREAD

**Issue by clarknelson** [dburles/meteor-google-maps#28]
Is there any support for event callbacks like "addListener" and "addDomListener"? Is there support for the whole v3 API or just basic functionality?

**Comment by dburles** [comment]
Once you've loaded the library you have full access to the maps object. So I would guess so!

**Comment by kodamirmo** [comment]
@dburles I assumed that once the library is loaded you can do this:

``` js
google.maps.event.addListener(map, click, function(){
     console.log('Click');
});
```

but, doesn't work for me, I did a pull request, where you can do this: 

``` js
map.addListener('click',function(){
      console.log('click!')
});
```

**Comment by dburles** [comment]
You're wanting to attach it to `map.instance` :)

**Comment by dburles** [comment]
See here in the docs: https://github.com/dburles/meteor-google-maps#googlemapsreadyname-callback

**Comment by kodamirmo** [comment]
You are right, my error was another variable call map in the same scope :(

**Comment by dburles** [comment]
Oh, no problem
