### ISSUE TITLE
Namespace Conflict with mrt:googlemaps

### ISSUE THREAD

**Issue by bmx269** [dburles/meteor-google-maps#3]
There is a namespace conflict with https://github.com/drewjw81/meteor-googlemaps that prevents both from being loaded in a project, which is bad, since the other project is older, and has been used as a dependency for a lot of other packages.

**Comment by dburles** [comment]
Not sure what the solution is here. Perhaps if you're needing to use both, fork this package and change GoogleMaps to something else. I'd then suggest pulling the fork into your project by using a git submodule.

**Comment by bmx269** [comment]
I was thinking maybe you would be interested combining efforts on that project? An idea.

**Comment by dburles** [comment]
Not sure, see that project is still under the mrt namespace, so not exactly a highlight package as it stands. The conflicting `GoogleMaps` name is unfortunate, I'm a bit reluctant to change it however since I'm sure that the issue you're encountering isn't probably all that common

**Comment by bmx269** [comment]
The repo just got taken over, it was updated 3 days ago

**Comment by dburles** [comment]
I realise but we must consider that this package has now been established for over a month with a significantly different API.

**Comment by mattkrick** [comment]
i don't see it as an issue, if you look at the code for the other package it's just a bloated way to paste in a script tag. With this one you get a namespaced map object that you can reference after creation and it lets you avoid a window.onload event which is otherwise necessary so all the tiles load.
