### ISSUE TITLE
Multiple Marker on the same Map.

### ISSUE THREAD

**Issue by ralphievolt** [dburles/meteor-google-maps#31]
How do I add multiple Marker on the same map? Your example only shows that the helper is return a single location.

My application will get the present location of the user which I am able to do so using the geolocation and the only problem is how to show on the map other marker based on my collection.

**Comment by pmwisdom** [comment]
``` javascript
new google.maps.Marker({
      position: new google.maps.LatLng(47.12414, 121.242),
      map: map.instance
    });
```

If you run this in a loop or in succession you will get that many markers on the map. Every time you call new google.maps.Marker a new marker will be created for the map, as long as your map option is the same each time.

If you were going to do geolocation....

``` javascript
Template.watchMap.onCreated(function() {
    GoogleMaps.ready('watchMap', function (map) {
        //Watch users position
        navigator.geolocation.watchPosition(function (pos) {
            //Every time we get a new location from the gps, make a new marker on the map
            new google.maps.Marker({
                position: new google.maps.LatLng(pos.coords.latitude, pos.coords.longitude),
                map: map.instance
            });
        }, function (err) {
            console.log("GPS ERROR", err);
        });
    });
});
```

**Comment by dburles** [comment]
@ralphievolt this may also help http://meteorcapture.com/how-to-create-a-reactive-google-map/

**Comment by ralphievolt** [comment]
Thanks guys..I'll try these inputs.
