### ISSUE TITLE
Maps ready not firing on app to foreground with cordova

### ISSUE THREAD

**Issue by pmwisdom** [dburles/meteor-google-maps#32]
As per example I set up my code, if the map renders, the first time the marker will be created. Then if you push the app into the background, and then launch back into the foreground, the map will refresh without creating the marker. Essentially, the ready call in the onCreated never gets called again. So the map refreshes without any of the ready information.

To get around this, I've put my ready function inside the helper, and it works as a workaround for now, however, the downside is you cant launch anything reactive from the ready function or in the helper at all, because obviously the map will just keep re rendering every time anything reactive changes.

Test this out on any device (cordova):

``` javascript
Template.map.onCreated(function () {
    GoogleMaps.ready('map', function(map){
        new google.maps.Marker({
            position: new google.maps.LatLng(47.617974, -122.321506),
            map: map.instance
        }); 
    });
});

Template.map.helpers({
    mapOptions: function() {
        return {
            center: new google.maps.LatLng(47.617974, -122.321506)
        }
    }
});
```

**Comment by dburles** [comment]
Hey @pmwisdom interesting bug there, what device (or devices?) are you seeing the bug on? I wouldn't have expected `onCreated` to not fire.

**Comment by pmwisdom** [comment]
Devices that I test on are iPhone 4s, 5, 6, for apple, and I have a nexus 5 for android. All of them see that same issue. When you enter the app from the background ( app still running in background) and with the map previously rendered to the foreground, you can see the map flash quickly, and re render, like the helper is re-firing, but not the ready function. I tried putting the ready function in rendered as well, but it didn't seem to work any differently.

**Comment by dburles** [comment]
Can you confirm this same bug happens on the [demo app](https://github.com/dburles/meteor-google-maps-demo)?

**Comment by dburles** [comment]
I realise it's basically the same code that you've pasted above, though your `mapOptions` helper is missing the check on `GoogleMaps.loaded()`

**Comment by pmwisdom** [comment]
Oops yeah, I did miss that, got it in the real code though.

**Comment by pmwisdom** [comment]
@dburles  I'll load that up on a phone when I get the chance and report back.

**Comment by dburles** [comment]
That'd be great, if it's no good, I'll take a look into it.

**Comment by pmwisdom** [comment]
Hey, looks like this was again another issue with my own setup. If you want to know the issue, I was returning a cursor.findOne in my routes data (which I used in the corresponding template), which caused the route to hit every time the object changed, which I normally wouldnt notice, aside from the map reloading. Feel like thats pretty weird behavior of iron router. To solve I just made a helper that returned that cursor instead and wah-lah, non refreshing map.

**Comment by pmwisdom** [comment]
Btw if you want your demo example to work out of the box with cordova, create a mobile-config.js file at the root and put

``` javascript
App.accessRule('*.google.com/*');
App.accessRule('*.googleapis.com/*');
App.accessRule('*.gstatic.com/*');
```

In it. Cheers!

**Comment by dburles** [comment]
Thanks, I'll put that in the docs as I've seen many people run into confusion with that.
