### ISSUE TITLE
map continually refreshes in firefox and cordova

### ISSUE THREAD

**Issue by lusilva** [dburles/meteor-google-maps#34]
Hello,

I'm creating a cordova app and have your map on one of the pages, but every time I go to the page the map continually refreshes. This also happens in firefox. I'm using the meteor-ionic framework, not sure if this could be the cause.

I'm passing in the options like so:

```
Template.riderDashboard.helpers({
  dashboardMapOptions: function() {
    // Make sure the maps API has loaded
    if (GoogleMaps.loaded()) {
      // Map initialization options
      return {
        center: new google.maps.LatLng(-37.8136, 144.9631),
        zoom: 15,
        // Disable all controls from the map, to make it look nicer on mobile.
        panControl: false,
        zoomControl: false,
        mapTypeControl: false,
        scaleControl: false,
        streetViewControl: false,
        overviewMapControl: false
      };
    }
  }
});
```

and in my view:

```
{{> googleMap name="dashboardMap" options=dashboardMapOptions}}
```

Any idea what could be causing this? I'm not using any reactiveVars in the options, so not sure why it continually updates.

I'm using Meteor 1.1.0.2

Thanks

**Comment by dburles** [comment]
Hey @lusilva hard to say exactly what might be the cause. Are you able to reproduce the bug in a new app that contains only the bare minimum code required to display the map?

**Comment by lusilva** [comment]
Just did a major refractoring and the problem doesn't seem to appear anymore, not sure what was causing it originally.
