### ISSUE TITLE
Initialise with hidden map

### ISSUE THREAD

**Issue by ganySA** [dburles/meteor-google-maps#35]
Hi

Firstly thanks a lot for such a great library really makes working with maps a breeze.

I have a question regarding usage when i would like to start off with the map hidden... display:none on the container div. it seems that later on the map behaves strangely. 

Is there a way to re-init the blaze component wrapper after i make display:block?

**Comment by dburles** [comment]
Hey thanks @ganySA. You can just do this:

```
{{#if showMap}}
  {{> googleMap ...}}
{{/if}}
```

**Comment by ganySA** [comment]
Great thanks! Works perfectly.

**Comment by ganySA** [comment]
It seems that the googleMaps ready function doesnt fire if i use the #if statements - any idea where i should place this? 

```
Template.orgRegister.rendered = function () {
    GoogleMaps.ready('orgAddress', function (map) {
```

**Comment by dburles** [comment]
Oh, try place the map inside a containing template with which to attach to the onCreated callback like:

``` js
Template.foo.onCreated(function() {
  GoogleMaps.ready(...
});
```

```
<template name="foo">
  {{> googleMap ...}}
</template>
```

```
<body>
{{#if showMap}}
  {{> foo}}
{{/if}}
</body>
```

**Comment by ganySA** [comment]
Thanks that did it!
