### ISSUE TITLE
Issue when using this along with autoform

### ISSUE THREAD

**Issue by theroadrunnershow** [dburles/meteor-google-maps#39]
Hi there, this package is awesome. This question is not related to this package, but more of why this does not work with yogiben:autoform-map. I was using the yogiben:autoform-map for my input form to make it easy. The form was working until I added dburles:meteor-google-maps. After I added this package, I got a TypeError.

Please check this link for details : 
http://stackoverflow.com/questions/29886354/meteor-autoform-maps-google-maps-package-error

Could you please provide guidance? Your help is appreciated!
Thanks.

**Comment by dburles** [comment]
Hey @theroadrunnershow the answer as you are probably now aware is there's an unfortunate conflict with the `GoogleMaps` namespace.

**Comment by theroadrunnershow** [comment]
@dburles 
Is there a recommended way to get around the conflict? Or am I limited to using only one of the packages for now in my app? The thing is that your package is very nice for viewing places which have already been marked. 
But yogiben's package allows me to create markers very easily (with almost no new code). Thats the reason I opted to choose both.
I am hoping there is a workaround?

**Comment by dburles** [comment]
It might be a nice idea for @yogiben to update his autoform map package to perhaps use this package instead of `mrt:googlemaps`. There's no way to work around the conflict unfortunately as the mrt:googlemaps package doesn't correctly export `GoogleMaps`

**Comment by kabalin** [comment]
It seems this issue can be closed: https://github.com/yogiben/meteor-autoform-map/commit/3de87cabd356774ee7ae2186b14c32b3673b5f66

Great package, thanks!

**Comment by dburles** [comment]
Great, thanks @kabalin !
