### ISSUE TITLE
Initialized callback option?

### ISSUE THREAD

**Issue by micahalcorn** [dburles/meteor-google-maps#4]
I have a need for running a function once the plugin itself has been initialized (as opposed to the initialization of an individual map). I noticed that you are setting the callback param to `_initialize()`, which simply sets the `_loaded` value. Would it make sense to allow for a callback option in `load()` or is there a more obvious way to supplement the callback?

**Comment by dburles** [comment]
hey @micahalcorn you can do something like this:

``` js
Tracker.autorun(function() {
  if (GoogleMaps.loaded()) {
    // do something
  }
});
```

**Comment by micahalcorn** [comment]
Simple enough, thanks.
