### ISSUE TITLE
How to load google maps places script?

### ISSUE THREAD

**Issue by theroadrunnershow** [dburles/meteor-google-maps#40]
HI @dburles 
I am trying to implement this:
https://developers.google.com/maps/documentation/javascript/examples/places-searchbox

I am unable to find a way to load this script. I get this error: TypeError: Cannot read property 'SearchBox' of undefined

I tried to load this script in multiple ways:
1.http://www.manuel-schoebel.com/blog/use-meteor-iron-router-waiton-to-load-external-javascript
2. meteor auto-loader

But every time I get error: It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.

Do you recommend a way to load the places script?

**Comment by dburles** [comment]
Hi @theroadrunnershow just load the map like so: `GoogleMaps.load({ libraries: 'places' });`

**Comment by dburles** [comment]
See here: https://github.com/dburles/meteor-google-maps#googlemapsloadoptions

**Comment by theroadrunnershow** [comment]
Ah my bad, should have read in detail! Thanks for the help!

**Comment by dburles** [comment]
No prob
