### ISSUE TITLE
passing a cursor in options

### ISSUE THREAD

**Issue by kevohagan** [dburles/meteor-google-maps#41]
Enhancement:

What are your thoughts on passing in a cursor in options on template initialization, something similar to 

https://github.com/meteor/mobile-packages/blob/master/examples/solomo/packages/google-maps/maps.js#L53

I think it could be useful!

**Comment by dburles** [comment]
Hey @kevohagan sounds like a great idea for an addon package :)

**Comment by kevohagan** [comment]
Challenge accepted!
