### ISSUE TITLE
I can not see map at mobile device, but on web work well. 

### ISSUE THREAD

**Issue by misteral** [dburles/meteor-google-maps#42]
I try to use 
meteor run android-device
internet connection is present.

http://my_visit_app.meteor.com/
https://github.com/misteral/my_visit_app

Please help.

**Comment by dburles** [comment]
Hey @misteral my guess is that you need to configure some access rules. See here: https://github.com/dburles/meteor-google-maps#mobile-platforms

**Comment by misteral** [comment]
@dburles, David, the very usefull answer. Sorry create my app at 5am.
