### ISSUE TITLE
ReferenceError: google is not defined and InfoBox is not defined

### ISSUE THREAD

**Issue by rahultank1993** [dburles/meteor-google-maps#44]
I want use infobox https://code.google.com/p/google-maps-utility-library-v3/source/browse/trunk/infobox/src/infobox.js?r=49 in my project 

i also put infobox.js file in client/lib/js/infobox.js

it given error
my code is

var myOptions = {
            disableAutoPan: true
            ,content: $("#imgR").html()
            ,isHidden: false
            ,boxStyle: {
                textAlign: "center"
                ,fontSize: "8pt"
                ,width: "18px"
            }
            ,pixelOffset: new google.maps.Size(-7, 0)
            ,position: point
            ,closeBoxURL: ""
            ,pane: "mapPane"
            ,enableEventPropagation: true
        };
        var infowin = new InfoBox(myOptions);
        infowin.open(map.instance);

**Comment by dburles** [comment]
Hey I've just added a new method `loadUtilityLibrary` https://github.com/dburles/meteor-google-maps#googlemapsloadutilitylibrarypathtolibraryjs which may fix this issue.

**Comment by rahultank1993** [comment]
thank you so much, it is work for me

**Comment by leizard** [comment]
Hi @rahultank1993 , I met the exact problem and don't know where to put `GoogleMaps. loadUtilityLibrary(path/to/infobox.js)` . Could you help me please ?

**Comment by dburles** [comment]
@leizard most likely alongside where you call `GoogleMaps.load()`

**Comment by leizard** [comment]
Hi @dburles, I put infobox.js in my public folder and call `GoogleMaps.loadUtilityLibrary('infobox.js')` after the `GoogleMaps.load()` and it works. But if I put infobox.js in my client folder and call `GoogleMaps.loadUtilityLibrary('client/infobox.js')`, it yields `Uncaught ReferenceError: google is not defined` . Do I have to put the file in public folder to make it work ?

**Comment by dburles** [comment]
Yep, public folder otherwise it won't work

**Comment by leizard** [comment]
@dburles thanh you.
