### ISSUE TITLE
using mapStyles shows the default map style at first

### ISSUE THREAD

**Issue by josephdburdick** [dburles/meteor-google-maps#46]
Hi @dburles, I have the following code in my map's template js file:

```
Template.Map.created = function () {
  GoogleMaps.ready('map', function(map) {
    map.instance.setOptions({styles: mapStyle});
        var marker = new google.maps.Marker({
      position: map.options.center,
      animation: google.maps.Animation.DROP,
      map: map.instance
    });

    var marker = new google.maps.Marker({
      position: new google.maps.LatLng(Session.get('lat'), Session.get('lon')),
      icon: constants.icons.svg["map-star"],
      map: map.instance,
      title: "Your Geolocation"
    });   

        var center;
        function calculateCenter() {
          center = map.instance.getCenter();
        }

        $(window).resize(function(){
            map.instance.setCenter(center);
        });

  });
}
```

Check out the 3rd line of code there where I set the map styles before the map element element is supposed to be rendered. What happens is that the template loads with your Google Maps plugins loaded but the styles are set to the default Google Maps' colors before refreshing with the right styles. Any possibility we can skip the double refresh?

**Comment by dburles** [comment]
Hey @josephdburdick you should be able to pass in the styles directly to the map options helper.

**Comment by josephdburdick** [comment]
@dburles dude... that is sooo much better. Way faster now. :fist: Thanks!
