### ISSUE TITLE
Stupid question map container height at 80% of display height

### ISSUE THREAD

**Issue by teknologist** [dburles/meteor-google-maps#47]
I have been struggling to set a height for the container div dynamically so it takes 80% of the total height.

How would you do this?

Have been googling around but found nothing that works with meteor so far.

Any advice ?

Many thanks in advance!

**Comment by teknologist** [comment]
FYI,

I have trying setting height via $() at 'rendered' and 'created' template events but it doesn't work.

**Comment by josephdburdick** [comment]
If you want the map to be 80% of the viewport height you can use vh (viewport height) units.

For example:

```
.map{
   height: 80vh;
}
```
