### ISSUE TITLE
Reactive display of Map using googleMap template 

### ISSUE THREAD

**Issue by alexofob** [dburles/meteor-google-maps#48]
Hi there,

I would like to implement a functionality to show users a map of a city that they have already added to their profile when they log in. And then give them the option to update their address using the map.

Basically, I want to use the geocoding functionality to achieve the functionality. However my concern is whether I can still use the googleMap template to display after getting the lat and lng from the geocoding API to set the mapOptions.

As this geocoding works asynchronously, I am using a callback to return the mapOptions in a Session object and returning it to the mapOptions parameter of the googleMap template via a helper (basically returning a  Session.get("mapOptions").

This does not seem to work, and I am thinking that may be the googleMap template does not support such reactive map display.

I will appreciate some feedback on this.

Thanks.

**Comment by dburles** [comment]
Hey @alexofob I wrote up an example of a way to do this in the [gitter chat](https://gitter.im/dburles/meteor-google-maps?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). I'll paste it here.

Wrap the `{{> googleMap ...}}` call within an `{{#if ...}}` helper that returns `true` once any reactive sources required in the init options return something.

``` js
Template.example.helpers({
  someCondition: function() {
    return !! Session.get('mapZoom');
  },
  mapOptions: function() {
    if (GoogleMaps.loaded()) {
      return {
        center: new google.maps.LatLng(-37.8136, 144.9631),
        zoom: Session.get('mapZoom')
      };
    }
  }
});
```

``` handlebars
{{#if someCondition}}
  {{> googleMap name="test" options=mapOptions}}
{{/if}}
```

that way it will only render (and call mapOptions) once the mapZoom session has been set.

You can do exactly the same thing using your geocoding session.
