### ISSUE TITLE
How to handle reactive marker clustering?

### ISSUE THREAD

**Issue by josephdburdick** [dburles/meteor-google-maps#49]
Hi, how would one handle reactive map marker clustering? https://developers.google.com/maps/articles/toomanymarkers

**Comment by dburles** [comment]
Hey @josephdburdick sorry, that's not something I've looked into. Though it might be a nice thing to expand the reactive maps example on. Perhaps try ask in the [gitter chat](https://camo.githubusercontent.com/da2edb525cde1455a622c58c0effc3a90b9a181c/68747470733a2f2f6261646765732e6769747465722e696d2f4a6f696e253230436861742e737667).

**Comment by josephdburdick** [comment]
Ok well I'll do that. I'll close this now and if I come up with a solution I'll reopen here and post the solution.
