### ISSUE TITLE
Using geolocation the the package

### ISSUE THREAD

**Issue by JulianSamarjiev** [dburles/meteor-google-maps#51]
This issue I am having: http://stackoverflow.com/questions/31192327/current-position-on-map-meteor
I have been stuck on this for 3 days, any ideas how I should tackle this? @dburles

**Comment by dburles** [comment]
Hey @JulianSamarjiev sorry I haven't got back to this sooner, did you manage to figure it out? I can't see any code in your example for creating a marker. Perhaps look into Meteor's own package for geolocation, it may simplify things.

Seems like a simple idea for an example app, I may take a look into doing a blog post on that :)

**Comment by JulianSamarjiev** [comment]
Cheers for getting back, I will take a second crack at it once I get some time :) keep up the good work :)!
