### ISSUE TITLE
Placemarks sometimes go invisible

### ISSUE THREAD

**Issue by clarkritchie** [dburles/meteor-google-maps#52]
Any thoughts on why my markers might randomly disappear (or at least become invisible) after refitting the map?

I am following the pattern in the [tutorial](http://meteorcapture.com/how-to-create-a-reactive-google-map/), i.e. I have a `markers`
In [this video demonstration](http://screencast.com/t/DmPVRetWhk) I am calling `setBounds` after the click event on the select -- that zooms in on the selected placemark.  Clicking "Show All" just calls `setBounds` again with my array of all placemarks so all are visible.  You can see that it works the first time, but sometimes some/all of my markers go invisible until I zoom in/out using the wheel on my mouse.

```
function setBounds(map, markers) {
    // markers is an object (not array) of markers
    var bounds = new google.maps.LatLngBounds();
    _.each(markers, function(val, key) {
        bounds.extend(val.getPosition());
    });
    map.fitBounds(bounds);
}
```

The only place I am doing a `setMap(null)` on a marker is in the removed function on my observer.

google.maps.version
"3.21.5a"

**Comment by dburles** [comment]
Hey sorry I haven't got back to this one @clarkritchie, did you manage to sort it out?

**Comment by clarkritchie** [comment]
At the moment there's nothing I can do repeatedly.  I've been working with this library full-time for a month, and sometimes (very rarely) I've seen the `dragend` event leave the original marker in its place.  And sometimes markers just don't draw.  A quick zoom out/in or hard refresh fixes both.  Occasionally I get two `click` events (despite `event.stop()`) when I'm certain there's just one.  Again, these are just observations and all extremely rare.  Will post a new ticket when I can repeat.  My gut says its something deep down between Blaze and the Maps library...

**Comment by dburles** [comment]
Hmm, sounds like a tricky one to trace. Keep me posted if you do come across anything repeatable.
