### ISSUE TITLE
Cached view

### ISSUE THREAD

**Issue by damienrobson** [dburles/meteor-google-maps#54]
I'm loading the package via IronRouter as instructed in the readme, which is working great. However, if I switch to a different page that also uses Maps, the map loads but does not re-centre on the new location I'm providing it with. 

Is it better to unload the maps (if so, how do I do this?) when I leave the first page? Or can I force it to relocate if the page is changed?

**Comment by damienrobson** [comment]
Never mind - I've managed to sort it by force-refreshing! :+1:

**Comment by dburles** [comment]
Hey you shouldn't have to "force refresh" just check that you're passing in the correct zoom and center for each map in their respective map options helper

**Comment by damienrobson** [comment]
Thanks, I'll update it as you recommend.
