### ISSUE TITLE
Control Positioning not working

### ISSUE THREAD

**Issue by chackerian** [dburles/meteor-google-maps#55]
I'm trying to add a search bar and position it on the top left corner of the google maps window. According to the google maps api your supposed to use the following line to align the search once it has been created `map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);`

Currently my helper function is:

`````` Template.meetuprequest.helpers({
  offerMapOptions: function () {
    if ( GoogleMaps.loaded() ) {
      var lat = Listing.find({ _id: id }).fetch()[0].lat;
      var lng = Listing.find({ _id: id }).fetch()[0].lng;
      var map = new google.maps.LatLng(lat, lng);
      var input = $("pac-input")[0];
      // var instance = GoogleMaps.maps.offerImage.instance;
      // instance.controls[google.maps.ControlPosition.TOP_LEFT].push(input);
      return {
        center: map,
        // searchBox: new google.maps.places.SearchBox((input)),
        zoom: 18
      };```
``````

My onCreated code block is:

```
Template.meetuprequest.onCreated( function () {
  GoogleMaps.ready('offerImage', function (map) {
    var searchBox = new google.maps.places.SearchBox((input));
    var input = $("pac-input")[0];
    // var instance = GoogleMaps.maps.offerImage.instance;
    // instance.controls[google.maps.ControlPosition.TOP_LEFT].push(input);
  });
});
```

My HTML file looks like:

```
<input id="pac-input" class="controls" type="text" placeholder="Search Box">
            <div class="mrapi">
                {{> googleMap name="offerImage" options=offerMapOptions }}
            </div>
```

Unfortunately it seems to be doing nothing. The search bar remains above the maps and doesn't reposition.

**Comment by chackerian** [comment]
Whoops, my jquery is wrong. `var input = $("pac-input")[0];` Forgot the #. It now works.

**Comment by chackerian** [comment]
Well it isn't working exactly as I want it to actually. When I go to the page with the map, it doesn't reposition the search bar immediately. If I refresh the page it works properly but without doing this it remains above the map.

**Comment by chackerian** [comment]
Any Ideas?

**Comment by dburles** [comment]
Hey @chackerian might be worth asking in the [gitter chat](https://camo.githubusercontent.com/da2edb525cde1455a622c58c0effc3a90b9a181c/68747470733a2f2f6261646765732e6769747465722e696d2f4a6f696e253230436861742e737667) also it would be worth creating a simple reproduction application people can clone

**Comment by chackerian** [comment]
I'll make sure to check that out in the future if I get stuck. Turns out I just had to load google maps slightly differently and now it seems to be working ok.
