### ISSUE TITLE
Package added but not detected

### ISSUE THREAD

**Issue by Jonfor** [dburles/meteor-google-maps#56]
I can add the meteor package perfectly fine to my project but nothing is actually detected when trying to use it. For example, trying to do `GoogleMaps.load()` does not work because it cannot find `GoogleMaps` despite the package being added correctly and appearing when doing `meteor show`.

I think the issue that the package.js has to be updated to support the latest version of meteor.

**Comment by dburles** [comment]
Hey @Jonfor would you mind providing the exact error message? Also make sure you're not referencing `GoogleMaps` on the server.

**Comment by Jonfor** [comment]
Of course now that I try to reproduce the error I'm not getting it. I was get an error along the lines of 'The reference GoogleMaps is undefined', even though I had the package installed.

I found that while I still had this issue I could install the package locally and it worked fine. Not sure if adding it locally and then switching over to the online package changed something?

My IDE (WebStorm) still complains that GoogleMaps is an 'unresolved variable or type' but it runs fine.

**Comment by Jonfor** [comment]
I got it to give me the error again. I have no idea what caused it to start up again. Also just noticed it is complaining about `google` and not `GoogleMaps` this time. I think this stack trace is a different issue; It might be because I load the library on the client only but attempt to load it on the server. Here is the stack trace:

`I20150716-14:58:34.253(-4)? Exception from task: ReferenceError: google is not defined
I20150716-14:58:34.254(-4)?     at Object.Markers.find.observe.added (app/hike.js:44:34)
I20150716-14:58:34.254(-4)?     at [object Object].observeChangesCallbacks.added (packages/minimongo/observe.js:153:1)
I20150716-14:58:34.254(-4)?     at self.applyChange.added (packages/minimongo/observe.js:53:1)
I20150716-14:58:34.254(-4)?     at packages/mongo/observe_multiplex.js:208:1
I20150716-14:58:34.254(-4)?     at [object Object]._.extend.forEach (packages/id-map/id-map.js:48:1)
I20150716-14:58:34.254(-4)?     at [object Object]._.extend._sendAdds (packages/mongo/observe_multiplex.js:200:1)
I20150716-14:58:34.254(-4)?     at packages/mongo/observe_multiplex.js:51:1
I20150716-14:58:34.254(-4)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
I20150716-14:58:34.255(-4)?     at Object.task (packages/meteor/dynamics_nodejs.js:121:1)
I20150716-14:58:34.255(-4)?     at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
I20150716-14:58:34.255(-4)? Exception while invoking method 'observeChanges' ReferenceError: google is not defined
I20150716-14:58:34.255(-4)?     at Object.Future.wait (/home/jonfor/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20150716-14:58:34.255(-4)?     at [object Object]._.extend.runTask (packages/meteor/fiber_helpers.js:81:1)
I20150716-14:58:34.255(-4)?     at [object Object]._.extend.addHandleAndSendInitialAdds (packages/mongo/observe_multiplex.js:47:1)
I20150716-14:58:34.255(-4)?     at [object Object].MongoConnection._observeChanges (packages/mongo/mongo_driver.js:1179:1)
I20150716-14:58:34.255(-4)?     at [object Object].Cursor.observeChanges (packages/mongo/mongo_driver.js:854:1)
I20150716-14:58:34.256(-4)?     at Function.LocalCollection._observeFromObserveChanges (packages/minimongo/observe.js:177:1)
I20150716-14:58:34.256(-4)?     at [object Object].Cursor.observe (packages/mongo/mongo_driver.js:848:1)
I20150716-14:58:34.256(-4)?     at [object Object].Meteor.methods.observeChanges (app/hike.js:41:24)
I20150716-14:58:34.256(-4)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150716-14:58:34.256(-4)?     at packages/ddp/livedata_server.js:648:1
I20150716-14:58:34.256(-4)?     - - - - -
I20150716-14:58:34.256(-4)?     at Object.Markers.find.observe.added (app/hike.js:44:34)
I20150716-14:58:34.256(-4)?     at [object Object].observeChangesCallbacks.added (packages/minimongo/observe.js:153:1)
I20150716-14:58:34.256(-4)?     at self.applyChange.added (packages/minimongo/observe.js:53:1)
I20150716-14:58:34.257(-4)?     at packages/mongo/observe_multiplex.js:208:1
I20150716-14:58:34.257(-4)?     at [object Object]._.extend.forEach (packages/id-map/id-map.js:48:1)
I20150716-14:58:34.257(-4)?     at [object Object]._.extend._sendAdds (packages/mongo/observe_multiplex.js:200:1)
I20150716-14:58:34.257(-4)?     at packages/mongo/observe_multiplex.js:51:1
I20150716-14:58:34.257(-4)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
I20150716-14:58:34.257(-4)?     at Object.task (packages/meteor/dynamics_nodejs.js:121:1)
I20150716-14:58:34.257(-4)?     at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)`

**Comment by Jonfor** [comment]
Pretty sure the issue was just me not loading in the client. I'll close the issue.
