### ISSUE TITLE
Customize Template Helper?

### ISSUE THREAD

**Issue by espoal** [dburles/meteor-google-maps#59]
I'm porting a commercial theme to Meteor, and it uses google maps. I'm using your package, but I've met some issues:

1)  The map div requires a give ID and Class to be shown correctly, otherwise the height is 0 and the .ready() callback is never invoked. Right now I solve this with:

```
Template.contact.onRendered(function () {

    $('.map-canvas').attr('id', 'map-simple').addClass('map-contact');

});
```

But it causes a FUOC and it is slow. How can I extend default helper with this class and id?

2) The options helper is called twice, and this is why there is a need for the .loaded() check. Is there a way to add the map dynamically, e.g. via console? I would use this to solve the FUOC problem and help debug.

3) The LatLng literal doesn't work. It works when I load the API manually. It complains that a.lng() is not a function. Is this a Meteor thing?

great package btw :+1:

**Comment by dburles** [comment]
Hey @servermeta 
1. I'm sure you can easily solve this by modifying the CSS. If there's a good reason why that won't work I'll definitely look at adding the ability to pass in attributes to the wrapping div.
2. You shouldn't need to go to that length, it's designed to work this way as the options helper is designed to be called when the map is created/initialized. `loaded()` is a reactive method.
3. Not sure exactly what's up here what's `a`?

**Comment by espoal** [comment]
@dburles 
Sorry for the late reply, I've been very busy.

1) I was porting a commercial theme to meteor. The code to port was not very well written, but I solved it by rewriting part of the CSS. 

2) I solved this by rewriting the logic and using flow router.

3) Can you use LatLng literals instead of objects? It gives me an error with your package, but not with the original library.

I would also like to thank you for all the amazing work you are doing for the community.

**Comment by dburles** [comment]
Thanks @servermeta. Can you show me a snippet of how you're trying to use LatLng literals?

**Comment by espoal** [comment]
Sure! Right now I refactored the code so I don't need this anymore, but the commercial theme I was porting had some poor CSS which required to fix CSS with onReady. This caused some recomputation, slowing down stuff. 

I had an helper which provided google maps options:

```
Template.realEstate.helpers({
    mapOptions: function () {
        if (GoogleMaps.loaded()) {
            return mapOptions = {
                center: new google.maps.LatLng(51.541216, -0.095678),
                styles: [
                    {
                        "featureType": "road",
                        "elementType": "labels",
                        "stylers": [
                            {"visibility": "simplified"},
                            {"lightness": 20}]
                    },
                    {
                        "featureType": "administrative.land_parcel",
                        "elementType": "all",
                        "stylers": [
                            {"visibility": "off"}]
                    [...]
            };
        }
    }
});

```

I have to check if google maps is loaded in this helper. A simpler solution would be to use a latlng literal, so I could provide the data even before the loading of maps. 

so

```
center: {lat: -34.397, lng: 150.644},
```
