### ISSUE TITLE
Including GoogleMaps.load() in Meteor.startup gives the error "TypeError: window.GoogleMaps is undefined"

### ISSUE THREAD

**Issue by mr2day** [dburles/meteor-google-maps#66]
Hi,

I'm trying to include a map in a large Meteor app. The map doesn't show, and I keep seeing the error "TypeError: window.GoogleMaps is undefined" in console. I simplified things (deleted the templates, etc) until I had only two things remaining: the package 'dburles:google-maps', and the 'GoogleMaps.load()' in Meteor.startup. No template, no helper, so the error comes from here.
I made a meteor app from scratch, to see if the package works, and obviousy works with no error. I was able to see the map and add whatever markers I wanted. Do you have any idea what could cause this error in the large app? Maybe it interferes with other packages? I removed some, and still see the error. There are too many of them to enumerate here.

**Comment by hypogealgaol** [comment]
So somehwere you have

```
Meteor.startup(function() {
    GoogleMaps.load();
});
```

I think that means that somewhere else you have to have a `GoogleMaps.loaded()` and then return with the options and push that to a template. Were you still getting errors even with that?

**Comment by mr2day** [comment]
Yes. `GoogleMaps.loaded()` is never true.

**Comment by hypogealgaol** [comment]
if GoogleMaps is undefined that means there's probably some error with the package installation. Is there a way for you to confirm that the package is actually being used by the app? If you think there is some package interaction interfering with the google-maps then I think there isn't much way to figure it out besides stochastically testing it. If you deleted everything from your large scale app until there was nothing left except for the package and the load AND you also did the same thing with an app from scratch but it works, then my guess is that the package must never have been working in the large scale app in the first place.

Also make sure the relative structure is similar in your scratch app and your large scale app after you strip it down to make sure as well

**Comment by mr2day** [comment]
Yes, if I call `GoogleMaps.load()` in Meteor.startup without including the package, I get a huge error in console. If I include it, the only error I get is `TypeError: window.GoogleMaps is undefined`. So the package is read by the app.

**Comment by mr2day** [comment]
Very strange.
Packages are added to the app in a package.js file, this way:
`Package.onUse(function(api) {
  api.use([
    'dburles:google-maps'
  ], ['client']);
});`
and that's why it wasn't working. But all other 40 packages the app uses are added this way and they all work, only this one doesn't.

I added it the usual way, with `meteor add dburles:google-maps`, and now it works.

**Comment by hypogealgaol** [comment]
idk if that's verbatim but you didn't close your onUse call

**Comment by mr2day** [comment]
Ok, I did. This is just example code. In the app, the onUse call is very big, and properly closed. It would make no sense to paste it all here.

**Comment by hypogealgaol** [comment]
i understand, just making sure. glad you solved the issue though, I wonder if that still translates to there being a bug in the package though?

**Comment by mr2day** [comment]
It would be interesting to make an app from scratch, where the packages are added with an onUse call, and see if google-maps works. If not, it means that it cannot be used this way, which might be inconvenient for some developers that use meteor for more than just rapid prototyping.

**Comment by dburles** [comment]
Hey @mr2day would you mind pasting the contents of your `.meteor/packages` file?

**Comment by mr2day** [comment]
`# Meteor packages used by this project, one per line.`
`# Check this file (and the other files in this directory) into your repository.`
`#`
`# 'meteor add' and 'meteor remove' will edit this file for you,`
`# but you can also edit it by hand.`

`meteor-platform`
`driller-shop`
`sinda:fancybox`
`dburles:google-maps`

... but the majority of packages used by the app are kept in a packages.js file, not in this one.

**Comment by dburles** [comment]
@mr2day looks like it's not really an issue with this package in particular but another package may be doing something funky to the window object, it just happens to affect the maps package.

**Comment by lucfranken** [comment]
If I include the package it does not work. Equal to the issues discussed above.

I suspect because of globals being used and meteor is capturing the variables into the local package.

Fix which seems to work for me:

``` javascript
  // include the package as in documentation
  api.use('dburles:google-maps');

  // this is not in the docs but makes the global variable available
  if (api.export) {
    api.export('GoogleMaps', 'client');
  }
```

**Comment by YannDanthu** [comment]
Hi,
the trick does not work for me :(

tried to do api.use global or client, same for api.export.
and all possible combination.

no luck.
I had to put the dependence back in .meteor/packages

**Comment by lucfranken** [comment]
Understand that that post is from quite some versions of Meteor back. So the solution or fix might be different.

**Comment by dburles** [comment]
Just to be clear are you guys wanting to load the package from a package (not through meteor add) and then have GoogleMaps available to the application scope?

**Comment by dburles** [comment]
and if that's the case you'll want to use `api.imply('dburles:google-maps@1.1.5', 'client');` to make `GoogleMaps` available to the application

**Comment by YannDanthu** [comment]
Hi,
yes that's correct. 
We would like to load the dep from a package.
And load it with `api.imply('dburles:google-maps@1.1.5', 'client');`
or simply `api.imply('dburles:google-maps@1.1.5');`

regs

**Comment by lucfranken** [comment]
It's old but my use case was:
- global app
  - my package
    - maps package

And I wanted to use the map in my package.

Think you are right @dburles it has the same effect. Still it feels not right, why should I make a sub package global if I just want to use it in my package?

**Comment by dburles** [comment]
If you're just wanting to use it in your package then `api.use` is suitable
