### ISSUE TITLE
Marker object doesn't show up when geo refresh 

### ISSUE THREAD

**Issue by fortunebubble** [dburles/meteor-google-maps#67]
the meteorpad demo
http://meteorpad.com/pad/efKWAphP8FcHH7Kcs/Geo_loc_example
based on the tutorial 
http://meteorcapture.com/reactive-geolocation-with-google-maps/
The marker doesn't show up again if one wait for the GPS location to get refresh

**Comment by dburles** [comment]
Hey @fortunebubble basically the problem was that meteorpad was choosing to use an older version of the package rather than the latest (1.1.1). See here: http://meteorpad.com/pad/fr7Jc4Qi385damFsC/Copy%20of%20Geo_loc_example

**Comment by fortunebubble** [comment]
I see, thank you @dburles
