### ISSUE TITLE
Wrapping googlemaps template on React component

### ISSUE THREAD

**Issue by OkuraSt** [dburles/meteor-google-maps#69]
Hi, this is not an issue, its a question I hope someone can help me.

Im trying to wrap the googlemaps template into a react component but i cant get it to work.
Using flow router, I load the GoogleMap like so:

FlowRouter.route('/googletest', {
    action() {
        GoogleMaps.load();
        ReactLayout.render(MainLayout,{
            content: <GoogleTest />
        });
    }
});

The GoogleTest component looks like this:

GoogleTest = React.createClass({
    componentDidMount() {
        this.view = Blaze.render(Template.mapWrapper,
            React.findDOMNode(this.refs.mapContainer));
    },
    exampleMapOptions: function() {
        // Make sure the maps API has loaded
        if (GoogleMaps.loaded()) {
            // Map initialization options
            return {
                center: new google.maps.LatLng(-37.8136, 144.9631),
                zoom: 8
            };
        }
    },
    render(){
        return <span ref="mapContainer" />;
    }
});

And this is the simple MainLayout component

MainLayout = React.createClass({

```
render() {
    return (
        <div className="overlay">
            <main>
                <div>
                    {this.props.content}
                </div>
            </main>

        </div>
    );
}
```

});

The mapWrapper template I'm using looks like this:

<template name="mapWrapper">
    <div class="map-container">
        {{> googleMap name="exampleMap" options=exampleMapOptions}}
    </div>
</template>

I've tried to move the GoogleMaps.load() to the component code (on componentDidMount) but no look either.

Thanks for your time.

**Comment by dburles** [comment]
https://github.com/dburles/meteor-google-maps-react-example

**Comment by OkuraSt** [comment]
Thank you for your time, with your example I got it to work.
