### ISSUE TITLE
Initial load failing when page accessed direct from url

### ISSUE THREAD

**Issue by mattkrick** [dburles/meteor-google-maps#7]
This may be an iron router issue, but since I can only reproduce it with google maps, I wanted to pick your brain.

I have a page with a map on it, the result is the same whether the script is loaded onStartup or onBeforeAction in the router.

If I refresh the page, everything is OK.
If I access the page via a link, everything is OK.
If I load the page by typing in the url, only the upper left tile loads. Disabling the cache has no effect. Any thoughts on the cause? Unfortunately, I don't know meteor well enough to know the difference between what it does on a refresh & what it does on a GET request...

Additionally, there's about a 10% chance that it fails to enter the callback inside GoogleMaps.ready (but touches lines before and after the .ready call). I can only reproduce this part in Chrome Canary 42, so we can ignore it for now, although I'd wager the 2 are related.

**Comment by dburles** [comment]
Hey @mattkrick thanks for this, would you mind creating a simple reproduction project I could clone and try out? That would help me a great deal with debugging.

**Comment by mattkrick** [comment]
Sure thing, unfortunately, it works with simple scenarios. I'm slowly adding more complexity until I can get a failure, but it may take awhile. I'm pretty sure I'm causing a race condition somewhere, just can't pin it down...

**Comment by dburles** [comment]
Yeah it's interesting as I've encountered something similar but very very rarely

**Comment by mattkrick** [comment]
All I can conclude is that too many front-loaded resources can sometimes cause a failure.
When I stick a bunch of junk in the lib or add a ton of link imports (polymer elements) , I can increase failure rates to near 100%. When I remove or lazy-load them, I can't get it to fail at all.

Interestingly enough, when I uninstall the google-maps package & instead clone the files into my repo, failure rates increase as well, even when I stick them in `/lib`. That tells me file load order definitely plays a part in this.

Two solutions:
Add a delay on map creation. It's not pretty, but you could allow the user to specify the time delay in the options object.

``` javascript
        setTimeout(function () {
          GoogleMaps._create(data.name, {
            instance: new google.maps.Map(canvas, data.options),
            options: data.options
          });
        }, 300)
```

A more elegant solution would be to append 3 lines to the end of `_create` to refresh the map once everything is done loading.  I _think_ this is pretty foolproof, but given enough time, I'll probably break it somehow...

``` javascript
   _create: function (name, options) {
      this.maps[name] = {
        instance: options.instance,
        options: options.options
      };
      this._ready(name, this.maps[name]);
      var self = this;
      google.maps.event.addListenerOnce(this.maps[name].instance, 'idle', function() {
        google.maps.event.trigger(self.maps[name].instance, 'resize');
      })
    }
```

**Comment by dburles** [comment]
Hey thanks for digging into it a bit. I'd like to have a reliable repro setup to investigate a bit more. I'll see if I can reproduce the bug.
