### ISSUE TITLE
Pan to current location

### ISSUE THREAD

**Issue by andrerfneves** [dburles/meteor-google-maps#71]
Great package! Building a prototype with it right now and I love how extensive Gmaps v3 is. However, why is it that when I click my button I do not get a panTo function being called?

``` javascript
Template.home.rendered = function() {
    function recenterMapOnGeoLoc() {
        GoogleMaps.maps.map.instance.panTo(GeoMarker.getPosition());
    }
}
```

``` html
<button class="button button-clear pull-right button-positive" onclick="recenterMapOnGeoLoc();">
      {{> ionIcon icon='android-locate' class="pastport-icons"}}
</button>
```

The map works fine and the Geolocation does too. My marker appears i perfectly. What I want to be able to do is click a button for the user to be panned back to their current location. Any idea why the code above isn't working? My map instance is actually 'map' so that's why I'm using         GoogleMaps.maps.map.instance.panTo(). However, whenever the button is clicked I receive a `ReferenceError: recenterMapOnGeoLoc is not defined` error. Why isn't the function available for the click event?!

Thanks!

**Comment by dburles** [comment]
Hey @andrerfneves use [Template events](http://docs.meteor.com/#/full/template_events) for event handling in Meteor.

**Comment by andrerfneves** [comment]
Yeah that's what I did at first, but I assumed the Google Maps API might have limitations and whatnot because it also didn't work.

``` javascript
Template.home.events({
    'click #currentLocation': function() {
        GoogleMaps.maps.map.instance.panTo(GeoMarker.getPosition());
    }
});
```

``` html
<button class="button button-clear pull-right button-positive" id="currentLocation">
      {{> ionIcon icon='android-locate' class="pastport-icons"}}
</button>
```

Am I not calling the map instance correctly?

Thanks for the help @dburles!

**Comment by dburles** [comment]
Not sure exactly, are there any errors?

**Comment by andrerfneves** [comment]
There are none. For some reason it seems that my click event isn't being registered on the DOM element at all. A `console.log('clicked')` call on the template event doesn't appear on the console. So I'll have a look at it. 

Regardless, if I were to figure this out, the `GoogleMaps.maps.map.instance.panTo(POSITION-LAT, POSITION-LNG)` call makes sense/should work? (I only have 1 map instance called 'map')

**Comment by dburles** [comment]
Should be easy enough to see, just try it out in the browser console

**Comment by andrerfneves** [comment]
Even with specific lat and long values, the call only gives me an error object. I can't seem to get any more specific than this on the error for some reason.

<img width="602" alt="screen shot 2015-08-27 at 10 23 15 pm" src="https://cloud.githubusercontent.com/assets/2574011/9537849/b614e2e0-4d0b-11e5-8978-72e45f7f2d9c.png">

I'm working on getting more of my code here. Just have to select the necessary code. I'll update this in a little while.

**Comment by dburles** [comment]
Check the map docs the `panTo` method takes a `latLng` object.

**Comment by andrerfneves** [comment]
As it turns out this is the call for a gmap with a name of 'map'.
Thanks @dburles.

``` javascript
GoogleMaps.maps.map.instance.panTo(Geolocation.latLng());
```
