### ISSUE TITLE
Inside a webix template-driven widget

### ISSUE THREAD

**Issue by ouya99** [dburles/meteor-google-maps#72]
Hi,

I posted this issue in the forum, but maybe in here would be appropriate too.

https://forums.meteor.com/t/google-map-inside-webix-widget/9027/1

I would like to add your plugin to a webix-template-driven widget, but I do not see how to pass the "options" parameter. When running it without it I get a NPE on the options data.

Thank you for your help!
java99

**Comment by dburles** [comment]
Hey rather than using the blaze template, in this case instead try the `create` method

**Comment by dburles** [comment]
Any luck?

**Comment by ouya99** [comment]
I assume your advice to use the create method would generally work

but I gave up due to other problems too and switched to meteoric - with ionic the template is working fine!
