### ISSUE TITLE
No Access Control Allow Origin Error

### ISSUE THREAD

**Issue by chackerian** [dburles/meteor-google-maps#73]
I'm receiving the following error in Chrome. Tested it out in Firefox and google maps works fine. Google maps is loading on the page correctly but throws this error when I try using the Autocomplete search feature. 

<img width="1277" alt="screen shot 2015-08-31 at 9 46 00 pm" src="https://cloud.githubusercontent.com/assets/5833874/9594733/e7eac432-502c-11e5-83b9-fd9851a61cfa.png">

**Comment by dburles** [comment]
Hey @chackerian it looks like you're using the `browser-policy` package, you'll need to configure it to allow the required domains.

**Comment by chackerian** [comment]
I don't think I'm using that unless it is hidden. I certainly didn't install that package and meteor list doesn't show it. On the version deployed online this error is not given when I search. It is only displayed on localhost. Could I possibly need a different google api link for both?

**Comment by amnevins** [comment]
App.accessRule("http://*"); 

in your mobile-config.js file
