### ISSUE TITLE
Map options not updating after route change

### ISSUE THREAD

**Issue by nsookhan** [dburles/meteor-google-maps#74]
Hi,

I'm having trouble getting the map options to update after a route change (using Iron-router) even when other data in the template is being updated.

To replicate this issue:
1. Go to https://planetrocks.utsc.utoronto.ca/
2. Click on a marker on the main map (or type in any letter in the search bar) and go to a specific site.
3. Type in any letter on the top right search bar (or enter a site name like 'courtice') and you should see that text changes however the map location does not refresh.
   (However, if I console.log out the helper containing the options, it will show the correct coordinates associated with the route.)

This also occurs in template views with direct url's to the Site (I.e Search ['Don Valley Brickworks'](https://planetrocks.utsc.utoronto.ca/S15) and you will see a string of urls: 'Sites S7, S8, S9, S10')

In my template controller:

``` javascript
Meteor.subscribe("sites");

Template.site_view.helpers({

site_view_map_options: function() {

      var id = Router.current().params._site;
      // gets the url :_site

    var site_doc = Sites.findOne({siteID: id});
      // retrieves entire document that for the respective id
    console.log(site_doc.Lat);
    // Makes sure the maps API has loaded
    if (GoogleMaps.loaded()) {
      // Map initialization options

      return {
        center: new google.maps.LatLng(site_doc.Lat, site_doc.Lon),
        zoom: site_doc.mapzoom,
        mapTypeId: google.maps.MapTypeId.SATELLITE,
        tilt: 45
      };
    }   
  }

});

Template.site_view.onCreated(function() {

  GoogleMaps.ready('site_view_map', function(map) {
    // Adds the site marker once ready (already centered)
    var marker = new google.maps.Marker({
      position: map.options.center,
      map: map.instance
    });
  });
});

Template.site_view.onDestroyed(function() {
    console.log('destroyed');
});
```

The rest of the source code for the map template can be found here: 
https://github.com/nsookhan/lets-rock/tree/master/client/templates/site_view

Router:
https://github.com/nsookhan/lets-rock/blob/master/client/router.js

Search box routing (uses Easy Search https://atmospherejs.com/matteodem/easy-search):
https://github.com/nsookhan/lets-rock/blob/master/client/templates/navigation/navigation.js

Thank you for looking into this and have a great day

PS: I'm still relatively new to Meteor, I think this was a reactivity issue so I looked into past issues of this topic with no avail.

**Comment by dburles** [comment]
Hey @nsookhan the map options are designed to return once. If you're wanting to update things reactively such as on a route change, you're best to do it inside of an `autorun` in the `ready` callback. See here for an example https://github.com/dburles/geolocation-example/blob/master/googlemaps-geolocation.js#L8-L37

**Comment by beverlycodes** [comment]
Usually, if I want to do something like re-center the map onto a new location, I use a lat+long string as the map's key property.  This tells React to completely drop the existing map from the DOM and render a new one.

**Comment by nsookhan** [comment]
Thanks @dburles, my friend and I finally looked into this issue. Thanks for your input as well @ryanfields. .

**Comment by nsookhan** [comment]
And sorry for the late reply!
