### ISSUE TITLE
Google API 403

### ISSUE THREAD

**Issue by beverlycodes** [dburles/meteor-google-maps#75]
If I leave my app open in a browser for a long period of time (not sure what the exact length of time to trigger is, happens when it was left up overnight), Google's API starts returning 403s for all requests.  There doesn't seem to be a programmatic way to fix this, and worse, no way to detect it except looking at the error console.  All I can do is refresh (which is fine for me, but not so fine for users out in the wild).  Has this been encountered before?  Is there a way to catch these 403s and maybe re-run GoogleMaps.load?

**Comment by dburles** [comment]
Hey @ryanfields that's a weird one, I've not encountered it myself. No luck googling the issue?

**Comment by dburles** [comment]
@ryanfields feel free to reopen if this is still an issue, though it seems unlikely it's a direct issue with this package
