### ISSUE TITLE
Supporting third party maps libraries

### ISSUE THREAD

**Issue by abdelba** [dburles/meteor-google-maps#76]
Hi,

It could be useful to have support for those who don't use the package's templates.
Using Leaflet I may write (with [leaflet-plugins](https://github.com/shramov/leaflet-plugins) plugin):

``` javascript
var googleLayer = new L.Google();
```

Which gives 

```
ReferenceError: google is not defined
```

Indeed, the `google` object is loaded by the Maps API script.
I can have `GoogleMaps.loaded()` returning `true` and `google` still undefined.

Is it possible to add an option to `GoogleMaps.loaded()` to solve this problem ?

**Comment by dburles** [comment]
Hey @AbdelBa I'm not sure I understand the exact problem. Do you have a simple example project that illustrates the problem? Take a look at https://github.com/dburles/meteor-google-maps#loadutilitylibrary and https://github.com/dburles/meteor-google-maps#create may help.
