### ISSUE TITLE
google.maps.places.Autocomplete class

### ISSUE THREAD

**Issue by garyfoo** [dburles/meteor-google-maps#77]
Hello, does anyone know if it's possible to access to google.maps.places.Autocomplete class through this package? A big thanks to anyone who can help with this :)

**Comment by dburles** [comment]
Hey @gfmr90 might this be what you're looking for? https://atmospherejs.com/jeremy/geocomplete

**Comment by eddieux** [comment]
Alternatively, I think you can load the Maps plus the Google Places API like this:

```
GoogleMaps.load({ libraries: 'places')});
```

and you will get the whole Autocomplete stuff, since it resides under google.maps.places.
