### ISSUE TITLE
Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.

### ISSUE THREAD

**Issue by felipesmendes** [dburles/meteor-google-maps#78]
When I access my aplication is given this error:

Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.

Before update to Meteor 1.2 was working...

**Comment by dburles** [comment]
Hey @felipesmendes works okay here, can you provide a reproduction?

**Comment by dburles** [comment]
@felipesmendes did you manage to solve this one?

**Comment by felipesmendes** [comment]
Yes, sorry for didn't reply, the bug it's because i was puting the `<script>` tag calling maps in template.
My fault!
 Thank You!
