### ISSUE TITLE
google map resize is not working 

### ISSUE THREAD

**Issue by wal-agardezi** [dburles/meteor-google-maps#79]
I am trying to resize the map like this google.maps.event.trigger(GoogleMaps.maps.exampleMaps , 'resize') is not working. Can you tell me why it is not working

**Comment by mariyaVj** [comment]
I am also trying  with this code . It is not working for me also.

**Comment by dburles** [comment]
If you believe this a bug with this package it would be super helpful if you could produce an example application that reproduces the issue, and as a bonus a working example outside of this package!

**Comment by Gardezi1** [comment]
@mariyaVj and @dburles  I kind of found the solution to it.  I was doing it wrong I had to access the  resize the instance of the map not exapmleMaps. I did it like this 

google,maps.event.trigger(GoogleMaps.maps.exampleMaps.instance , 'resize')

and at the end I would like to say that @dburles I mean no offence but please maintain your repo :)

**Comment by wal-agardezi** [comment]
@mariyaVj  and @dburles  I kind of found the solution to it. I was doing it wrong I had to access the resize the instance of the map not exapmleMaps. I did it like this

google,maps.event.trigger(GoogleMaps.maps.exampleMaps.instance , 'resize')

and at the end I would like to say that @dburles  I mean no offence but please maintain your repo :)

**Comment by dburles** [comment]
thanks @wal-agardezi
