### ISSUE TITLE
cant access visualization methods

### ISSUE THREAD

**Issue by philipobrien** [dburles/meteor-google-maps#80]
Hi, I am trying to replicate [this example](https://developers.google.com/chart/interactive/docs/gallery/geomap#regionsexample) but I'm getting errors related to this

``` js
var data = google.visualization.arrayToDataTable([
```

```
Uncaught TypeError: Cannot read property 'arrayToDataTable' of undefined
```

I am making sure `visualization` is loaded using 

``` js
Meteor.startup(function() {
        GoogleMaps.load({libraries: 'visualization'});
    });
```

but when I view the contents of `visualization` all I see is 

![image](https://cloud.githubusercontent.com/assets/1763813/10250741/8dd83b30-6924-11e5-8a79-035cd8105daf.png)

**Comment by dburles** [comment]
It appears as though it's perhaps loading a different version of the library than the one loaded via the google jsapi as in the example.
