### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by dcworldwide** [dburles/meteor-google-maps#81]
I've been noticing the following event in my console each time i load this package in my app

<img width="701" alt="screen shot 2015-10-07 at 14 19 37" src="https://cloud.githubusercontent.com/assets/4898751/10329036/cdcb7abc-6cfe-11e5-984b-fd51c0a31f58.png">

I'm using the latest chrome. 

It seems harmless as everything seems to work...but thought you should be aware of it

**Comment by dcworldwide** [comment]
I can confirm that this error fires on map scale change

**Comment by dburles** [comment]
Thanks @dcworldwide I think this is related to https://github.com/dburles/meteor-google-maps/issues/82 update to version 1.1.5 and hopefully that will fix the issue.
