### ISSUE TITLE
Help positioning  a pin on the middle of the map

### ISSUE THREAD

**Issue by jerocosio** [dburles/meteor-google-maps#83]
Hi, I'm having some trouble trying to set a pin on the center of the map. The first time I load the map everything works as I expect it and the pin is at the correct center of the map, and also when I refresh the page (on the browser) everything works fine, but when I access the url with the maps once it has been loaded before, the pin always appears some pixels above the actual center (please check this Youtube video  to check this problem ).

https://www.youtube.com/watch?v=tpNP2pOkgDk

I think this might be a problem with how the maps are loaded? Or could you give me any advice on how to fix this?

I am actually adding this pin like this:

//Inside GoogleMaps.ready:

```
setTimeout(function(){
        $('<div/>').addClass('centerMarker').appendTo(map.instance.getDiv());
      }, 400);
```

On a different CSS:

```
.map-container .centerMarker {
  position:absolute;
  /*url of the marker*/
  background:url(/iconos/marcadorVyno.gif) no-repeat;
  /*center the marker*/
  top:50%;
  left:50%;
  z-index:1;
  /*fix offset when needed*/
  margin-left:-12px;
  margin-top:-45px;
  /*size of the image*/
  height:45px;
  width:24px;
  cursor:pointer;
}
```

**Comment by dburles** [comment]
Hey @cosio55 did you manage to solve this? will close as it's not an issue with the package itself
