### ISSUE TITLE
GoogleMaps.load() not working on iOS (with Iron)

### ISSUE THREAD

**Issue by Loschcode** [dburles/meteor-google-maps#87]
I don't know if it's related to the package itself or Iron. The map is showing up correctly in my browser but when I try it out with iOS Simulator (iPhone 6 / iOS 8.3) it just never loads ... Here's a repository I setup for you to reproduce the problem

https://github.com/Loschcode/meteor-iron-google-maps-issue

I'm not sure it's a human mistake or an issue, but it's been hours i'm on it and i really don't get it

NOTE : I let the some alert() to fire on iOS to see the problem clearly.

**Comment by dburles** [comment]
Hey @Loschcode have you added the access rules? See: https://github.com/dburles/meteor-google-maps#mobile-platforms

**Comment by Loschcode** [comment]
It seems it was the problem, sorry i didn't close this issue ;)
