### ISSUE TITLE
The page was loaded over HTTPS, but requested an insecure image

### ISSUE THREAD

**Issue by minixxie** [dburles/meteor-google-maps#90]
We're using this package in a meteor project over HTTPS URL.
And it reports some Warning in the console saying this:
Mixed Content: The page at https://xxxxx was loaded over HTTPS, but requested an insecure image 'http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m2.png'.

We would like to know if there is a way in this package to specify to use HTTPS google map api?
Thank you very much.

Best wishes,
Simon

**Comment by dburles** [comment]
Hey @minixxie the package does load the main API over https are you loading in any other google maps libraries by any chance? (Within `GoogleMaps.load({ libraries: "..." })`)

**Comment by dburles** [comment]
Will close as this doesn't directly relate to an issue with this package
