### ISSUE TITLE
Why do I get an inaccessible marker at the map center?

### ISSUE THREAD

**Issue by JesperWe** [dburles/meteor-google-maps#92]
I do a very simple map component using Blaze Components (Only difference from standard Blaze is helpers and events go in the same class):

```
class thingMap extends BlazeComponent {
    onCreated() {
        super.onCreated();
    }

    onRendered() {
        GoogleMaps.load();
    }

    events() {
        return super.events().concat( {
        } );
    }

    thingMapOptions() {
        if( GoogleMaps.loaded() && Geolocation.latLng() ) {
            return {
                disableDefaultUI: true,
                center: { lat: 59, lng: 18 }, // Geolocation.latLng(),
                zoom: 8
            };
        }
    }
}

thingMap.register( 'thingMap' );

<template name="thingMap">
<div class="map-container">
    {{> googleMap name="thingMap" options=thingMapOptions}}
</div>
</template>
```

The map comes up nicely, but it has a fixed marker at the center location. Since I didn't create this marker I do not have a handle on it, so I can't get rid of it.

How can I get rid of this?

**Comment by dburles** [comment]
Hey @JesperWe are you able to reproduce it on a fresh Meteor project?

**Comment by JesperWe** [comment]
I ended up abandoning your package and rolled my own stuff into my BlazeComponent, which works as expected.
Sorry, I realize I am not being very helpful but I am under time pressure so I am not going to pursue this any further.
