### ISSUE TITLE
Blank map without any error in Chrome 46, IE 11

### ISSUE THREAD

**Issue by dandv** [dburles/meteor-google-maps#96]
Looks like I'm experiencing a variant of #33, but without console errors:

![image](https://cloud.githubusercontent.com/assets/33569/11420708/bcef4b4e-93e4-11e5-9a70-7a1d34b8eceb.png)

Demo at http://huawei.meteor.com or https://huawei.meteor.com. 

The repo is a simple educational app, an [Instagram clone](https://github.com/dandv/instagram-clone). It used to run fine in May 2015. `meteor update` didn't help.

Ad blockers disabled.

**Comment by dburles** [comment]
Thanks @dandv I also see a blank map there, will take a look

**Comment by dburles** [comment]
Hey @dandv this seems to be the culprit: https://github.com/dandv/instagram-clone/blob/master/client/photochat.css#L7

**Comment by dandv** [comment]
Thanks a lot, that fixes it!
