### ISSUE TITLE
Error: google is not defined

### ISSUE THREAD

**Issue by acamarata** [dburles/meteor-google-maps#98]
In my maps helper I have:

```
    if (GoogleMaps.loaded()) {
        return {
            center: new google.maps.LatLng(loc.lat, loc.lng),
            scrollwheel: false,
            disableDefaultUI: true,
            zoomControl: true,
            mapTypeId: google.maps.MapTypeId.SATELLITE,
            zoom: 18
        };
    }
```

Yet it breaks and the error in console is "google is not defined" for the line declaring "center"

**Comment by acamarata** [comment]
I am using `if (typeof google !== 'undefined')` as a temporary work around

**Comment by dburles** [comment]
Strange, how are you loading the library? Can you provide some more context?

**Comment by acamarata** [comment]
I am loading and initializing with startup:

```
Meteor.startup(function () {
    GoogleMaps.load();
    GoogleMaps.initialize();
});
```

While I am using the above code in the initial post within a map helper modeled on your example:

```
mapOptions: function () {
    var loc = Session.get('loc');

    //if (GoogleMaps.loaded()) {
    if (typeof google !== 'undefined') {
        return {
            center: new google.maps.LatLng(loc.lat, loc.lng),
            scrollwheel: false,
            disableDefaultUI: true,
            zoomControl: true,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            zoom: 12
        };
    }
},
```

That is the whole helper.

**Comment by dburles** [comment]
Ah the problem is you're calling the [initialize](https://github.com/dburles/meteor-google-maps#initialize) method. It's not required if you're loading the package using `GoogleMaps.load`.

**Comment by acamarata** [comment]
I commented out the initialize() method, used loaded() again and the error returned: google is not defined

Though going back to typeof without initialize still works..

**Comment by dburles** [comment]
Try the [example app](https://github.com/dburles/meteor-google-maps-demo) (it's super basic) and compare that with your application code, you may spot something gone awry.
