### ISSUE TITLE
How do I update the map with new Markers?

### ISSUE THREAD

**Issue by educkf** [dburles/meteor-google-maps#99]
Hello!
I have on my app an input bar that user can type the address, and then it should show a new pin for that address. The only issue is that it is only showing the Marker if I drag the map around or zoom in/out on it. I am pretty sure the issue is on `GoogleMaps.ready` stuff I am using to show this new marker. It is like this:

``` javascript
GoogleMaps.ready('map', function(map) {
     var marker = new google.maps.Marker({
          position: new google.maps.LatLng(newPositionLat,newPositionLng),
          title:"Hello World4",
          map: map.instance
     });
});
```

This code works, it is showing the Marker, not automatically, but only when I zoom in/out and the map need to "re-render". Is there some kind of `GoogleMaps.update` or something that automatically adds this new marker as soon I create it?

**Comment by dburles** [comment]
Hey @educkf take a look at [this example](http://meteorcapture.com/how-to-create-a-reactive-google-map) to see how's it's done

**Comment by dburles** [comment]
@educkf Did that solve the problem?
